# Unified UI - Market (Thị Trường) 📈

This notebook demonstrates how to use the **Market Layer** to retrieve realtime and historical pricing data for various asset classes. 

*Sổ tay này hướng dẫn cách sử dụng **Market Layer** để lấy dữ liệu giá thời gian thực và lịch sử cho nhiều loại tài sản khác nhau.*

<p>
  <a href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/unified-ui/02_Market.ipynb" target="_blank" style="display:inline-block; vertical-align:middle; margin-left:8px;">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" style="height:20px; vertical-align:middle;">
  </a>
  <a href="https://codespaces.new/thinh-vu/vnstock" target="_blank" style="display:inline-block; vertical-align:middle;">
    <img src="https://img.shields.io/badge/Open%20in-GitHub%20Codespaces-blue?logo=github" alt="Open in GitHub Codespaces" style="height:20px; vertical-align:middle;">
  </a>
</p>

---

### Sử dụng với Jupyter Notebook (Trong IDE)
Khi chạy Jupyter Notebook trực tiếp trong IDE (như Antigravity, VS Code, Cursor), để sử dụng được môi trường ảo `~/.venv`, bạn cần đăng ký nó dưới dạng một Kernel.

<details>
<summary><b>💡 <i>Click để xem hướng dẫn thiết lập chi tiết</i></b></summary>
<br>
Khi chạy Jupyter Notebook trực tiếp trong IDE (như Antigravity, VS Code, Cursor), để sử dụng được môi trường ảo `~/.venv`, bạn cần đăng ký nó dưới dạng một Kernel.

**1. Kích hoạt môi trường ảo**
(Mặc định do Vnstock Installer tạo ra, bạn có thể chỉnh lại path nếu cài ở vị trí khác)
```bash
# macOS / Linux
source ~/.venv/bin/activate
# Windows
~\.venv\Scripts\activate
```

2. Cài đặt thư viện kết nối (ipykernel)

```bash
python -m pip install ipykernel
```

3. Đăng ký Kernel với Jupyter

```bash
python -m ipykernel install --user --name=vnstock-venv --display-name "Python (Vnstock)"
```

4. Chọn Kernel trong IDE

Nhìn góc trên bên phải Notebook, click vào tên Kernel hiện tại (vd: Select Kernel hoặc Python 3.x.x).
Chọn Python (Vnstock) từ danh sách. (Tải lại cửa sổ nếu chưa thấy bằng tổ hợp phím `Ctrl`/`Cmd` + `Shift` + `P` sau đó tìm lệnh `Developer: Reload Window`).

In [18]:
from vnstock import Market

mkt = Market()

## 1. Equity Market / Thị Trường Cổ Phiếu

Retrieve OHLCV, trade history, order book, and other statistics for individual stocks.

*Lấy giá lịch sử, lịch sử lệnh, sổ lệnh, và các thống kê khác cho từng cổ phiếu.*

### Historical Price (OHLCV) / Lịch sử giá

In [19]:
mkt.equity("ACB").ohlcv(length=10, interval='1D')

                 time   open   high    low  close    volume
0 2026-04-14 07:00:00  23.95  24.15  23.80  24.00  15449600
1 2026-04-15 07:00:00  24.15  24.20  23.80  23.80   7254600
2 2026-04-16 07:00:00  23.90  23.90  23.60  23.65   8623100
3 2026-04-17 07:00:00  23.70  23.85  23.65  23.75   6073500
4 2026-04-20 07:00:00  23.85  24.00  23.75  23.95   8670200
5 2026-04-21 07:00:00  24.00  24.05  23.75  23.75   6823700
6 2026-04-22 07:00:00  23.75  23.80  23.55  23.60   8805900
7 2026-04-23 07:00:00  23.55  23.90  23.50  23.50  14035700
8 2026-04-24 07:00:00  23.55  23.60  23.30  23.40  17478700
9 2026-04-28 07:00:00  23.40  23.50  23.35  23.50   2986500

In [20]:
df_ohlcv = mkt.equity("ACB").ohlcv(start="2026-04-01", end="2026-04-10")
df_ohlcv

                 time   open   high    low  close    volume
0 2026-04-01 07:00:00  23.85  23.90  23.70  23.80   9883500
1 2026-04-02 07:00:00  23.70  23.70  23.30  23.60   9767900
2 2026-04-03 07:00:00  23.60  23.70  23.25  23.50  11386300
3 2026-04-06 07:00:00  23.50  23.50  23.20  23.25   5554000
4 2026-04-07 07:00:00  23.25  23.40  23.15  23.20  10472700
5 2026-04-08 07:00:00  23.70  24.15  23.55  24.10  19727300
6 2026-04-09 07:00:00  24.05  24.05  23.75  23.85   5141500
7 2026-04-10 07:00:00  24.10  24.20  23.85  23.85   8136300

### Intraday Trades / Bảng Chi tiết Lệnh (Time & Sales)

In [21]:
df_trades = mkt.equity("ACB").trades()
df_trades

,time,price,volume,match_type,id
0,2026-04-28 11:29:49,23.50,1000,buy,2026-04-28_112949_235000_1000
1,2026-04-28 11:29:43,23.45,2700,sell,2026-04-28_112943_234500_2700
2,2026-04-28 11:29:16,23.45,300,sell,2026-04-28_112916_234500_300
3,2026-04-28 11:29:10,23.45,1200,sell,2026-04-28_112910_234500_1200
4,2026-04-28 11:29:03,23.45,18300,buy,2026-04-28_112903_234500_18300
...,...,...,...,...,...
95,2026-04-28 11:10:54,23.50,1000,buy,2026-04-28_111054_235000_1000
96,2026-04-28 11:10:39,23.50,400,buy,2026-04-28_111039_235000_400
97,2026-04-28 11:10:34,23.45,6700,buy,2026-04-28_111034_234500_6700
98,2026-04-28 11:10:32,23.45,1000,buy,2026-04-28_111032_234500_1000
99,2026-04-28 11:10:24,23.45,1000,buy,2026-04-28_111024_234500_1000

### Quote / Bảng giá

In [22]:
mkt.equity(["ACB", "VCB"]).quote()

,symbol,time,exchange,ceiling_price,floor_price,reference_price,open_price,high_price,low_price,close_price,...,bid_vol_3,ask_price_1,ask_vol_1,ask_price_2,ask_vol_2,ask_price_3,ask_vol_3,foreign_buy_volume,foreign_sell_volume,foreign_room
0,ACB,1777350600396,HOSE,25000,21800,23400,23400,23500,23350,23500,...,296300,23500.0,89300,23550,42600,23600,251200,132000,1788000,135010505
1,VCB,1777355485088,HOSE,64800,56400,60600,60800,61500,60800,61000,...,155000,61100.0,28000,61200,63500,61300,78800,601600,624840,821327917

In [23]:
quote = mkt.equity("HPG").quote()
quote

,symbol,time,exchange,ceiling_price,floor_price,reference_price,open_price,high_price,low_price,close_price,...,bid_vol_3,ask_price_1,ask_vol_1,ask_price_2,ask_vol_2,ask_price_3,ask_vol_3,foreign_buy_volume,foreign_sell_volume,foreign_room
0,HPG,1777355472184,HOSE,29850,25950,27900,27800,28000,27800,27900,...,512900,27900.0,524300,27950,260700,28000,759600,430201,532723,2015140243

## 2. Index Market / Thị Trường Chỉ Số

Provides historical index points, current quotes and summary. 

*Cung cấp điểm chỉ số lịch sử, bảng giá hiện hành và cấu trúc tổng quan.*\n
\n
> **Note:** Từ phiên bản 3.1.0, Vnstock đã hỗ trợ lấy thông tin thống kê lịch sử giao dịch mở rộng của các loại chỉ số thông qua hàm trade_history().

In [24]:
df_vnindex = mkt.index("VNINDEX").ohlcv(start="2026-01-01", end="2026-03-01")
df_vnindex.head()

                 time     open     high      low    close      volume
0 2026-01-05 07:00:00  1787.13  1797.40  1775.19  1788.40   810900473
1 2026-01-06 07:00:00  1795.57  1817.06  1788.40  1816.27   838989917
2 2026-01-07 07:00:00  1832.23  1861.58  1816.27  1861.58   929077252
3 2026-01-08 07:00:00  1880.81  1888.33  1850.11  1855.56  1172488005
4 2026-01-09 07:00:00  1861.02  1880.16  1853.16  1867.90  1218660759

## 3. Futures & Warrant Market / Thị trường Phái sinh & Chứng quyền

Access futures and warrant markets directly using their respective symbols.

*Truy cập trực tiếp thị trường hợp đồng tương lai và chứng quyền thông qua mã.*

### Futures Market / Hợp Đồng Tương Lai

In [25]:
symbol_future = "VN30F1M"
df_vn30f = mkt.futures(symbol_future).ohlcv(start="2026-04-01", end="2026-04-27")
display(df_vn30f.head())

quote_vn30f = mkt.futures(symbol_future).quote()
quote_vn30f

                 time    open    high     low   close  volume
0 2026-04-01 07:00:00  1860.0  1880.0  1860.0  1879.6     381
1 2026-04-02 07:00:00  1860.0  1860.0  1838.2  1851.8     361
2 2026-04-03 07:00:00  1869.0  1871.2  1830.4  1839.8     370
3 2026-04-06 07:00:00  1830.0  1852.0  1830.0  1841.0     366
4 2026-04-07 07:00:00  1840.0  1856.1  1833.1  1851.9     377

,symbol,time,exchange,ceiling_price,floor_price,reference_price,open_price,high_price,low_price,close_price,...,ask_price_1,ask_vol_1,ask_price_2,ask_vol_2,ask_price_3,ask_vol_3,foreign_buy_volume,foreign_sell_volume,foreign_room,open_interest
0,41I1G5000,1777350600645,HNX,2156,1874,2015,2023,2044.5,2015,2040.4,...,2040.5,3,2040.6,5,2040.7,6,8484,7761,0,32253

### Warrant Market / Chứng Quyền

In [26]:
symbol_warrant = "CACB2511"

df_warrant = mkt.warrant(symbol_warrant).ohlcv(start="2026-02-01", end="2026-03-01")
display(df_warrant.head())

quote_warrant = mkt.warrant(symbol_warrant).quote()
quote_warrant

                 time  open  high   low  close  volume
0 2026-02-02 07:00:00  1.89  1.89  1.68   1.78  278100
1 2026-02-03 07:00:00  1.86  1.86  1.61   1.73  974100
2 2026-02-04 07:00:00  1.77  1.77  1.65   1.70   65700
3 2026-02-05 07:00:00  1.76  1.76  1.61   1.62  186100
4 2026-02-06 07:00:00  1.61  1.68  1.49   1.51  215600

,symbol,time,exchange,ceiling_price,floor_price,reference_price,open_price,high_price,low_price,close_price,...,bid_vol_3,ask_price_1,ask_vol_1,ask_price_2,ask_vol_2,ask_price_3,ask_vol_3,foreign_buy_volume,foreign_sell_volume,foreign_room
0,CACB2511,1777350546693,HOSE,2290,690,1490,1520,1520,1510,1510,...,15000,1520.0,2000,1530,100000,1540,200000,0,0,13000000

## 4. ETF & Fund Market / Thị Trường Quỹ

Retrieve data for ETFs and open-ended mutual funds.

*Lấy dữ liệu cho các chứng chỉ quỹ ETF và quỹ đầu tư mở.*

In [27]:
# ETF Historical / Giá lịch sử ETF
df_etf = mkt.etf("E1VFVN30").ohlcv(start="2026-02-01", end="2026-03-01")
display(df_etf.head())

quote_etf = mkt.etf("E1VFVN30").quote()
quote_etf

                 time   open   high    low  close   volume
0 2026-02-02 07:00:00  35.91  36.53  35.15  36.53  1155200
1 2026-02-03 07:00:00  36.00  36.00  35.79  35.97   174800
2 2026-02-04 07:00:00  35.99  36.00  35.00  35.70   580600
3 2026-02-05 07:00:00  35.69  35.69  35.06  35.29   333000
4 2026-02-06 07:00:00  35.29  35.29  34.35  34.97   798500

,symbol,time,exchange,ceiling_price,floor_price,reference_price,open_price,high_price,low_price,close_price,...,bid_vol_3,ask_price_1,ask_vol_1,ask_price_2,ask_vol_2,ask_price_3,ask_vol_3,foreign_buy_volume,foreign_sell_volume,foreign_room
0,E1VFVN30,1777355491990,HOSE,38270,33270,35770,35770,36000,35660,35780,...,500,35780.0,900,35790,5400,35800,7800,79048,78200,42244871

### Mutual Fund Market / Quỹ đầu tư mở

In [28]:
# Mutual Fund NAV / Lịch sử NAV Quỹ mở
df_nav = mkt.fund("VFIBS").history()
display(df_nav.head())

# Top Holding / Tỷ trọng phân bổ tài sản cao nhất
top_holding = mkt.fund("VFIBS").top_holding()
display(top_holding)

# Industry Holding / Quản lý theo nhóm ngành
industry = mkt.fund("VFIBS").industry_holding()
display(industry)

2026-04-28 12:51:41 - vnstock.explorer.fmarket.fund - INFO - Total number of funds currently listed on Fmarket: 63

         date  nav_per_unit
0  2017-04-25       10000.0
1  2017-04-29       10058.0
2  2017-05-09       10093.0
3  2017-05-16       10165.0
4  2017-05-23       10254.0

2026-04-28 12:51:41 - vnstock.explorer.fmarket.fund - INFO - Total number of funds currently listed on Fmarket: 63

,stock_code,industry,net_asset_percent,type_asset,update_at,fundId
0,MBB,Ngân hàng,8.19,STOCK,2026-04-07,23
1,BVH,Bảo hiểm,7.45,STOCK,2026-04-07,23
2,PNJ,Sản xuất Phụ trợ,5.46,STOCK,2026-04-07,23
3,HPG,Vật liệu xây dựng,5.36,STOCK,2026-04-07,23
4,VCB,Ngân hàng,4.96,STOCK,2026-04-07,23
5,CTG,Ngân hàng,4.71,STOCK,2026-04-07,23
6,REE,Thiết bị điện,4.32,STOCK,2026-04-07,23
7,CTR,Công nghệ và thông tin,3.87,STOCK,2026-04-07,23
8,GMD,Vận tải - Kho bãi,3.45,STOCK,2026-04-07,23
9,MWG,Bán lẻ,3.36,STOCK,2026-04-07,23

2026-04-28 12:51:41 - vnstock.explorer.fmarket.fund - INFO - Total number of funds currently listed on Fmarket: 63

                    industry  net_asset_percent
0                  Ngân hàng              19.80
1           Sản xuất Phụ trợ               9.27
2                   Bảo hiểm               8.79
3          Vật liệu xây dựng               7.86
4     Công nghệ và thông tin               7.42
5          Vận tải - Kho bãi               7.20
6                     Bán lẻ               5.22
7                   Tiện ích               4.76
8              Thiết bị điện               4.32
9                Chứng khoán               2.74
10         Chế biến thủy sản               2.39
11              Bất động sản               2.34
12    Sản xuất Hàng gia dụng               2.13
13                  Bán buôn               2.04
14  Sản xuất Nhựa - Hóa chất               1.96
15        Dịch vụ viễn thông               1.47

## 5. Market Wide / Bảng Giá Nhiều Mã

Efficiently query multiple symbols at once to fetch a real-time snapshot market board.

*Truy vấn nhiều mã cùng lúc một cách tối ưu để lấy tổng quan bảng giá thị trường.*

In [29]:
df_quotes = mkt.quote(["VIC", "TCB", "HPG", "VNM", "BID"])
df_quotes

,symbol,time,exchange,ceiling_price,floor_price,reference_price,open_price,high_price,low_price,close_price,...,bid_vol_3,ask_price_1,ask_vol_1,ask_price_2,ask_vol_2,ask_price_3,ask_vol_3,foreign_buy_volume,foreign_sell_volume,foreign_room
0,VIC,1777355486589,HOSE,226900,197300,212100,210000,226900,209800,226700,...,1200,226800.0,71200,226900,126800,0,0,1041531,383675,3453174441
1,TCB,1777350599506,HOSE,36600,31900,34250,35000,35000,34500,34600,...,212000,34650.0,41200,34700,674200,34750,500300,23200,0,0
2,HPG,1777355472184,HOSE,29850,25950,27900,27800,28000,27800,27900,...,512900,27900.0,524300,27950,260700,28000,759600,430201,532723,2015140243
3,VNM,1777355487489,HOSE,65600,57200,61400,61200,61300,60500,60900,...,65500,60900.0,1600,61000,10400,61100,5900,150104,527650,1067446838
4,BID,1777355461680,HOSE,43600,37900,40750,40900,41100,40800,40850,...,50900,40900.0,83600,40950,85700,41000,187600,125840,185650,943161698

## 6. International Markets / Thị Trường Quốc Tế

Preview of global assets data utilizing `ohlcv()` methods. Features are experimental and use Microsoft Finance (Binance và Dukascopy) natively.

*Bản thử nghiệm cung cấp dữ liệu tài sản quốc tế bằng cách sử dụng phương thức `ohlcv()`. Nhóm này sử dụng nguồn cung cấp từ Binance và ForexSB.*

## 3. Crypto

Sử dụng bộ Unified UI để lấy dữ liệu Spot từ thị trường Crypto (nguồn: sàn **Binance**). Hỗ trợ các endpoints như OHLCV, Sổ lệnh (Order Book), Lịch sử giao dịch (Intraday), và Báo giá nhanh (Quote).

In [30]:
from typing import Any
from vnstock import Market
from IPython.display import display

# Khởi tạo đối tượng Market và lấy dữ liệu cặp tiền số BTCUSDT qua domain Crypto
mkt = Market()
crypto = mkt.crypto('BTCUSDT')

print("-- 2. OHLCV Lịch sử (5 Nến ngày gần nhất) --")
crypto.ohlcv(interval='1d', limit=5)

-- 2. OHLCV Lịch sử (5 Nến ngày gần nhất) --

,time,open,high,low,close,volume
0,2026-01-18,2.515177e+09,2.517108e+09,2.501498e+09,2.503981e+09,421851759149621
1,2026-01-19,2.504014e+09,2.514291e+09,2.464195e+09,2.465395e+09,547921539843562
2,2026-01-20,2.465954e+09,2.466090e+09,2.424710e+09,2.436936e+09,1032010708909326
3,2026-01-21,2.436936e+09,2.443383e+09,2.312167e+09,2.325226e+09,1397411248246224
4,2026-01-22,2.325637e+09,2.381033e+09,2.296807e+09,2.353295e+09,1483180022680111
...,...,...,...,...,...,...
95,2026-04-23,2.010406e+09,2.092392e+09,2.005282e+09,2.059088e+09,1272704113951047
96,2026-04-24,2.059108e+09,2.071564e+09,2.027791e+09,2.060822e+09,1062544541106958
97,2026-04-25,2.060686e+09,2.068329e+09,2.035795e+09,2.039398e+09,863208342144846
98,2026-04-26,2.039448e+09,2.050650e+09,2.032272e+09,2.043524e+09,439788229420063
99,2026-04-27,2.043553e+09,2.078057e+09,2.036228e+09,2.071053e+09,565645671961180

## 4. Khám phá thị trường Ngoại hối & Hàng hoá Quốc tế

Các tham số:
- `interval`: Hỗ trợ chuẩn `1m`, `1h`, `4h`, `1d`, `1w`, `1M`. Có cơ chế gom nến tự động.
- `side`: Tùy chọn lấy giá `bid` (mặc định), `ask` hoặc `mid`.

In [31]:
print("-- 1. Tỷ giá Ngoại Hối EUR/USD (Interval 1 giờ, 5 nến) --")
df_forex = mkt.forex("EURUSD").ohlcv(interval="1h", length=5, side="mid")
display(df_forex.head())

-- 1. Tỷ giá Ngoại Hối EUR/USD (Interval 1 giờ, 5 nến) --

                 time  open  high   low  close    volume
0 2026-04-21 07:00:00  1.18  1.18  1.17   1.17 -99999902
1 2026-04-22 07:00:00  1.17  1.18  1.17   1.17 -99999902
2 2026-04-23 07:00:00  1.17  1.17  1.17   1.17 -99999902
3 2026-04-24 07:00:00  1.17  1.17  1.17   1.17 -99999902
4 2026-04-27 07:00:00  1.17  1.18  1.17   1.17 -99999902

In [32]:
print("-- 2. Lịch sử giá Vàng XAU/USD (Interval 1d, 5 nến) --")
df_gold = mkt.forex("XAUUSD").ohlcv(interval="1d", length=5)
display(df_gold)

-- 2. Lịch sử giá Vàng XAU/USD (Interval 1d, 5 nến) --

        time     open     high      low    close volume
0 2026-04-20  4788.93  4827.41  4735.39  4819.64   None
1 2026-04-21  4819.05  4832.29  4666.79  4711.67   None
2 2026-04-22  4720.80  4772.08  4700.29  4737.78   None
3 2026-04-23  4737.14  4752.10  4663.69  4692.69   None
4 2026-04-24  4692.24  4740.05  4657.07  4708.69   None

In [33]:
print("-- 3. Chỉ số Chứng khoán Dow Jones US30 (Interval 4h, 5 nến) --")
# Hỗ trợ mã ngắn USA30, thư viện sẽ tự động phân giải thành USA30.IDX-USD
df_dowjones = mkt.index("USA30", scope="global").ohlcv(interval="4h", length=5)
display(df_dowjones)

print("-- 4. Đổi Múi Giờ Dữ Liệu Thị Trường Quốc Tế --")
# Dukascopy mặc định trả dữ liệu tính theo chuẩn khung giờ Việt Nam (GMT+7).
# Bạn có thể sử dụng param timezone để đưa dữ liệu về trả chuẩn UTC (hoặc bất kỳ múi giờ nào khác)
df_utc = mkt.forex("EURUSD", timezone="UTC").ohlcv(interval="1d", length=5)
display(df_utc)

-- 3. Chỉ số Chứng khoán Dow Jones US30 (Interval 4h, 5 nến) --

                 time      open      high       low     close     volume
0 2026-04-21 08:00:00  49688.37  49848.69  49046.54  49149.38  476631324
1 2026-04-22 08:00:00  49271.50  49624.48  49271.50  49490.03  426419604
2 2026-04-23 08:00:00  49284.85  49522.94  48861.31  49310.32  455474869
3 2026-04-24 08:00:00  49320.29  49393.34  49085.75  49230.71  536956902
4 2026-04-27 08:00:00  49112.20  49353.69  49029.47  49167.79  514579972

-- 4. Đổi Múi Giờ Dữ Liệu Thị Trường Quốc Tế --

        time  open  high   low  close    volume
0 2026-04-21  1.18  1.18  1.17   1.17 -99999902
1 2026-04-22  1.17  1.18  1.17   1.17 -99999902
2 2026-04-23  1.17  1.17  1.17   1.17 -99999902
3 2026-04-24  1.17  1.17  1.17   1.17 -99999902
4 2026-04-27  1.17  1.18  1.17   1.17 -99999902

In [34]:
mkt.index("USA30", scope="global").ohlcv(interval="1d", length=15)

         time      open      high       low     close     volume
0  2026-04-07  46744.76  46744.76  46214.77  46584.46  450740630
1  2026-04-08  46978.17  48017.09  46978.17  47909.92  523711453
2  2026-04-09  47840.63  48323.95  47690.27  48185.80  445240684
3  2026-04-10  48199.39  48235.06  47856.18  47916.57  478304657
4  2026-04-13  47718.21  48221.37  47505.97  48218.25  455852061
5  2026-04-14  48272.03  48592.29  48192.30  48535.99  527919024
6  2026-04-15  48549.14  48709.01  48281.62  48463.72  529878644
7  2026-04-16  48557.82  48683.45  48337.38  48578.72  456611310
8  2026-04-17  48788.81  49717.98  48788.81  49447.43  585656030
9  2026-04-20  49422.37  49489.63  49245.60  49442.56  411275296
10 2026-04-21  49688.37  49848.69  49046.54  49149.38  476631324
11 2026-04-22  49271.50  49624.48  49271.50  49490.03  426419604
12 2026-04-23  49284.85  49522.94  48861.31  49310.32  455474869
13 2026-04-24  49320.29  49393.34  49085.75  49230.71  536956902
14 2026-04-27  49112.20  49353.69  49029.47  49167.79  514579972