# Dữ liệu Chứng khoán Việt Nam

Hướng dẫn sử dụng **vnstock** để truy xuất dữ liệu thị trường chứng khoán Việt Nam toàn diện bao gồm:
- Danh sách mã chứng khoán và thông tin thị trường
- Dữ liệu giá lịch sử và thời gian thực
- Thông tin doanh nghiệp và báo cáo tài chính
- Thống kê giao dịch và phân tích thị trường

**⚡ Lựa chọn nền tảng:**
- **GitHub Codespaces** (Khuyến nghị): Môi trường đầy đủ, không cần cài đặt Python phức tạp và không bị chặn IP từ nguồn VCI.
- **Google Colab**: Miễn phí với hỗ trợ lưu trữ trong Google Drive. Hiện tại đang bị VCI chặn IP, cần dùng proxy.

**Lưu ý:** Nếu gặp vấn đề chặn IP từ nguồn VCI trên Colab, hãy thử [GitHub Codespaces](https://github.com/features/codespaces).

<p>
  <a href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_quickstart_stock_vietnam.ipynb" target="_blank" style="display:inline-block; vertical-align:middle; margin-left:8px;">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" style="height:20px; vertical-align:middle;">
  </a>
  <a href="https://codespaces.new/thinh-vu/vnstock" target="_blank" style="display:inline-block; vertical-align:middle;">
    <img src="https://img.shields.io/badge/Open%20in-GitHub%20Codespaces-blue?logo=github" alt="Open in GitHub Codespaces" style="height:20px; vertical-align:middle;">
  </a>
</p>

## Mục lục

1. [Cài đặt & Thiết lập](#scrollTo=BJYQtG0B4-sq)
2. [Danh sách mã chứng khoán](#scrollTo=3Wh1-IOJ4-sr)
3. [Dữ liệu giá & Báo giá](#scrollTo=rdlN42Hl4-st)
4. [Thông tin doanh nghiệp](#scrollTo=fdN7Sobv4-sw)
5. [Báo cáo tài chính](#scrollTo=8r_laqBY4-sz)
6. [Giao dịch & Dữ liệu thị trường](#scrollTo=sz8ZmBjF4-sv)
7. [Bộ lọc cổ phiếu](#scrollTo=4hihIdQ74-sz)

**Nguồn dữ liệu:**
   - [KBS](https://kbbuddywts.kbsec.com.vn/) (Chứng khoán KB)
   - [VCI](https://trading.vietcap.com.vn/priceboard) (Chứng khoán Vietcap) >> Cần cài đặt vnstock trên máy tính cá nhân hoặc dịch vụ không thuộc Google Cloud để truy cập (do máy chủ VCI chặn dải IP từ Google)

<a id="installation"></a>
## I. Cài đặt & Thiết lập

### Cài đặt chuẩn

In [ ]:
# Cài đặt hoặc nâng cấp vnstock
!pip install -U vnstock

# Cài đặt từ mã nguồn Github
# !pip install git+https://github.com/thinh-vu/vnstock

### Xác thực người dùng

Phiên bản vnstock 3.4.0 bắt đầu hỗ trợ tính năng nhận diện người dùng miễn phí để mở khóa tính năng so với sử dụng theo chế độ khách.

- 🚀 Đăng ký API key để tăng giới hạn sử dụng:

    - Khách (Guest):
        - Phù hợp để thử nghiệm nhanh, xem thử tính năng. Quảng cáo hiện thường xuyên
        - 20 requests/phút - không cần đăng ký
        - Tải tối đa 4 kỳ báo cáo tài chính

    - Cộng đồng (Community):
        - Trải nghiệm tính năng thư viện, chưa muốn gắn bó. Quảng cáo hiện thường xuyên
        - 60 requests/phút - đăng ký miễn phí
        - Tải tối đa 8 kỳ báo cáo tài chính

    - Tài trợ (Sponsor):
        - Không quảng cáo
        - 3-5x số lượt requests/phút so với bản miễn phí.
        - Truy cập đầy đủ các kỳ báo cáo tài chính.
        - Ủng hộ dự án phát triển công cụ & cộng đồng

- 📌 Đăng nhập Google để tạo tài khoản và lấy API key miễn phí tại: https://vnstocks.com/login

In [ ]:
# Chạy lệnh và nhập API key theo hướng dẫn
from vnstock import register_user
register_user()
# hoặc nhập trực tiếp API key vào hàm register_user
# register_user('YOUR_API_KEY')

### Tải Vnstock Agent Guide

> Vnstock Agent Guide là bộ tài liệu hướng dẫn và tham chiếu cách sử dụng các thư viện trong hệ sinh thái Vnstock. Nhờ có Agent Guide, các công cụ AI Agent để viết code Python có thể hoạt động chính xác nhờ hướng dẫn và tham chiếu này - giúp bạn vibe coding tạo ra ứng dụng mình muốn mà không yêu cầu kiến thức kỹ thuật quá nhiều.

In [ ]:
# Bỏ dấu ! phía trươc nếu chạy code trong Terminal riêng 

# 1. Tải về bộ hướng dẫn
!git clone https://github.com/vnstock-hq/vnstock-agent-guide.git

# 2. Sao chép vào dự án của bạn (Chọn lệnh phù hợp với OS)

# macOS / Linux:
!cp -r vnstock-agent-guide/docs vnstock-agent-guide/.agent vnstock-agent-guide/.cursor vnstock-agent-guide/.github vnstock-agent-guide/AGENTS.md vnstock-agent-guide/CLAUDE.md vnstock-agent-guide/GEMINI.md ./

Lệnh riêng cho Windows (PowerShell):

```
Copy-Item -Path vnstock-agent-guide/docs, vnstock-agent-guide/.agent, vnstock-agent-guide/.cursor, vnstock-agent-guide/.github, vnstock-agent-guide/AGENTS.md, vnstock-agent-guide/CLAUDE.md, vnstock-agent-guide/GEMINI.md -Destination ./ -Recurse -Force
```

Sau khi bộ tài liệu sẵn sàng trong môi trường làm việc, bạn có thể duyệt qua các file và thêm file vào ngữ cảnh chat để AI có thể hiểu cách viết code chính xác sử dụng thư viện Vnstock.

### Nạp thư viện

Bây giờ bạn có thể import và sử dụng vnstock bình thường:

In [ ]:
# Import các module của vnstock
from vnstock import Listing, Quote, Company, Finance, Trading

# Cách khác: Import từ nguồn dữ liệu cụ thể
# from vnstock.explorer.vci import Listing, Quote, Company, Finance, Trading
# from vnstock.explorer.tcbs import Quote, Company, Finance, Trading

print("✅ Tất cả modules đã được import thành công!")

<a id="listings"></a>
## II. Danh sách mã chứng khoán

Lấy danh sách các cổ phiếu giao dịch trên các sàn Việt Nam (HOSE, HNX, UPCOM).

### KBS

#### Listing: Liệt kê danh sách chứng khoán

In [ ]:
# VCI là nguồn dữ liệu từ CK Vietcap bên cạnh nguồn từ TCBS
from vnstock import Listing
listing = Listing(source='KBS')

#### Danh sách tất cả mã CK niêm yết (đơn giản)

In [ ]:
listing.all_symbols()

#### Liệt kê mã CP theo sàn (đầy đủ)

In [ ]:
# Dữ liệu bao gồm tất cả các mã không kể đang niêm yết hay không
listing.symbols_by_exchange()

,symbol,organ_name,en_organ_name,exchange,type,id
0,DPP,CTCP Dược Đồng Nai,Dong Nai Pharmaceutical Joint Stock Company,UPCOM,stock,1
1,SDA,CTCP Simco Sông Đà,SIMCO Song Da Joint Stock Company,HNX,stock,1
2,CLH,CTCP Xi măng La Hiên VVMI,VVMI La Hien Cement Joint Stock Company,HNX,stock,1
3,DBT,CTCP Dược phẩm Bến Tre,Ben Tre Pharmaceutical Joint Stock Company,HOSE,stock,1
4,DND,CTCP Đầu tư Xây dựng và Vật liệu Đồng Nai,Dong Nai Material & Building Investment Joint ...,UPCOM,stock,1
...,...,...,...,...,...,...
1947,VBA124019,NaN,NaN,HNX,bond,5
1948,BVB125003,NaN,NaN,HNX,bond,5
1949,CTG123033,NaN,NaN,HNX,bond,5
1950,BAB125023,NaN,NaN,HNX,bond,5
1951,VIC124005,NaN,NaN,HNX,bond,5

#### Liệt kê mã CP theo ngành icb

In [ ]:
listing.symbols_by_industries()

    symbol  industry_code           industry_name
0      ABR              6  Công nghệ và thông tin
1      ADC              6  Công nghệ và thông tin
2      BED              6  Công nghệ và thông tin
3      CKV              6  Công nghệ và thông tin
4      CMG              6  Công nghệ và thông tin
..     ...            ...                     ...
692    TD6             10             Khai khoáng
693    THT             10             Khai khoáng
694    TMB             10             Khai khoáng
695    TNT             10             Khai khoáng
696    TVD             10             Khai khoáng

[697 rows x 3 columns]

#### Danh sách cổ phiếu theo nhóm

In [ ]:
# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
listing.symbols_by_group('VN30')

0     ACB
1     BCM
2     BID
3     CTG
4     DGC
5     FPT
6     GAS
7     GVR
8     HDB
9     HPG
10    LPB
11    MBB
12    MSN
13    MWG
14    PLX
15    SAB
16    SHB
17    SSB
18    SSI
19    STB
20    TCB
21    TPB
22    VCB
23    VHM
24    VIB
25    VIC
26    VJC
27    VNM
28    VPB
29    VRE
Name: symbol, dtype: object

### VCI

#### Khởi tạo đối tượng

In [ ]:
from vnstock import Listing

# Khởi tạo đối tượng Listing với nguồn VCI
listing = Listing(source='VCI')

#### Danh sách tất cả mã cổ phiếu (Đơn giản)

In [ ]:
# Lấy danh sách đơn giản tất cả mã chứng khoán
all_symbols = listing.all_symbols()
print(f"Tổng số mã: {len(all_symbols)}")
all_symbols.head(10)

Tổng số mã: 1727

  symbol                                         organ_name
0    YTC  Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1    YEG                     Công ty Cổ phần Tập đoàn Yeah1
2    YBM     Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3    YBC      Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4    XPH                    Công ty Cổ phần Xà phòng Hà Nội
5    XMP                Công ty Cổ phần Thủy điện Xuân Minh
6    XMD                  Công ty Cổ phần Xuân Mai - Đạo Tú
7    XMC        Công ty cổ phần Đầu tư và Xây dựng Xuân Mai
8    XLV         Công ty Cổ phần Xây lắp và Dịch vụ Sông Đà
9    XHC                  Công ty Cổ phần Xuân Hòa Việt Nam

#### Danh sách cổ phiếu theo sàn giao dịch (Đầy đủ)

In [ ]:
# Lấy thông tin chi tiết cho tất cả mã theo sàn giao dịch
# Bao gồm cả mã đang và đã ngừng niêm yết
by_exchange = listing.symbols_by_exchange()
by_exchange.head()

,symbol,exchange,type,organ_short_name,organ_name,product_grp_id
0,YTC,UPCOM,STOCK,XNK Y tế TP.HCM,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,UPX
1,YEG,HSX,STOCK,Tập đoàn Yeah1,Công ty Cổ phần Tập đoàn Yeah1,STO
2,YBM,HSX,STOCK,Khoáng sản CN Yên Bái,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái,STO
3,YBC,UPCOM,STOCK,Xi măng và Khoáng sản Yên Bái,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái,UPX
4,XPH,UPCOM,STOCK,Xà phòng Hà Nội,Công ty Cổ phần Xà phòng Hà Nội,UPX

#### Danh sách cổ phiếu theo nhóm

In [ ]:
# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
listing.symbols_by_group('VN30')

0     ACB
1     BCM
2     BID
3     CTG
4     DGC
5     FPT
6     GAS
7     GVR
8     HDB
9     HPG
10    LPB
11    MBB
12    MSN
13    MWG
14    PLX
15    SAB
16    SHB
17    SSB
18    SSI
19    STB
20    TCB
21    TPB
22    VCB
23    VHM
24    VIB
25    VIC
26    VJC
27    VNM
28    VPB
29    VRE
Name: symbol, dtype: object

#### Danh sách theo ngành (ICB)

In [ ]:
# Lấy danh sách cổ phiếu được nhóm theo ngành ICB
by_industry = listing.symbols_by_industries()
by_industry.head()

,symbol,organ_name,icb_name3,icb_name2,icb_name4,com_type_code,icb_code1,icb_code2,icb_code3,icb_code4
0,BQP,Công ty Cổ phần Nhựa chất lượng cao Bình Thuận,Hóa chất,Hóa chất,"Nhựa, cao su & sợi",CT,1000,1300,1350,1353
1,F88,Công ty Cổ phần Đầu tư F88,Dịch vụ tài chính,Dịch vụ tài chính,Tài chính cá nhân,CT,8000,8700,8770,8773
2,DVT,Trung tâm Đào tạo nghiệp vụ Giao thông vận tải...,Tư vấn & Hỗ trợ Kinh doanh,Hàng & Dịch vụ Công nghiệp,Đào tạo & Việc làm,CT,2000,2700,2790,2793
3,ABS,Công ty Cổ phần Dịch vụ Nông nghiệp Bình Thuận,Hóa chất,Hóa chất,"Sản phẩm hóa dầu, Nông dược & Hóa chất khác",CT,1000,1300,1350,1357
4,AFX,Công ty Cổ phần Xuất Nhập khẩu Nông sản Thực p...,Phân phối thực phẩm & dược phẩm,Bán lẻ,Phân phối thực phẩm,CT,5000,5300,5330,5337

#### Danh sách mã ngành theo mã icb

In [ ]:
listing.industries_icb()

,icb_name,en_icb_name,icb_code,level
0,Sản xuất Dầu khí,Oil & Gas Producers,0530,3
1,"Thiết bị, Dịch vụ và Phân phối Dầu khí","Oil Equipment, Services & Distribution",0570,3
2,Hóa chất,Chemicals,1350,3
3,Lâm nghiệp và Giấy,Forestry & Paper,1730,3
4,Kim loại,Industrial Metals & Mining,1750,3
...,...,...,...,...
150,Viễn thông,Telecommunications,6000,1
151,Tiện ích Cộng đồng,Utilities,7000,1
152,Tài chính,Financials,8000,1
153,Ngân hàng,Banks,8301,1
154,Công nghệ Thông tin,Technology,9000,1

#### Danh sách mã hợp đồng tương lai

In [ ]:
listing.all_future_indices()

0    41I1FB000
1    41I1G3000
2    41I1G6000
3    41I2FB000
4    41I2FC000
5    41I2G3000
6    41I2G6000
7    VN30F2512
Name: symbol, dtype: object

#### Danh sách mã trái phiếu chính phủ

In [ ]:
listing.all_government_bonds()

0    41B5G3000
1    41B5G6000
2    41BAG3000
3    41BAG6000
4    GB05F2512
5    GB10F2512
Name: symbol, dtype: object

#### Danh sách bộ chỉ số

In [ ]:
listing.all_indices()

,symbol,name,description,full_name,group,index_id,sector_id
0,VN30,VN30,30 cổ phiếu vốn hóa lớn nhất & thanh khoản tốt...,VN30 Index,HOSE Indices,5,NaN
1,VNMID,VNMID,Mid-Cap Index - nhóm cổ phiếu vốn hóa trung bình,VNMidCap Index,HOSE Indices,6,NaN
2,VNSML,VNSML,Small-Cap Index - nhóm cổ phiếu vốn hóa nhỏ,VNSmallCap Index,HOSE Indices,7,NaN
3,VN100,VN100,100 cổ phiếu có vốn hoá lớn nhất HOSE,VN100 Index,HOSE Indices,8,NaN
4,VNALL,VNALL,Tất cả cổ phiếu trên HOSE và HNX,VNAll Index,HOSE Indices,9,NaN
5,VNSI,VNSI,Vietnam Small-Cap Index,VNSI Index,HOSE Indices,21,NaN
6,VNIT,VNIT,Công nghệ thông tin,Information Technology Sector Index,Sector Indices,10,159.0
7,VNIND,VNIND,Công nghiệp,Industrials Sector Index,Sector Indices,11,155.0
8,VNCONS,VNCONS,Hàng tiêu dùng,Consumer Staples Index,Sector Indices,12,130.0
9,VNCOND,VNCOND,Hàng tiêu dùng thiết yếu,Consumer Discretionary Sector Index,Sector Indices,13,133.0
10,VNHEAL,VNHEAL,Chăm sóc sức khoẻ,Health Care Sector Index,Sector Indices,14,135.0
11,VNENE,VNENE,Năng lượng,Energy Sector Index,Sector Indices,15,154.0
12,VNUTI,VNUTI,Dịch vụ tiện ích,Utilities Sector Index,Sector Indices,16,150.0
13,VNREAL,VNREAL,Bất động sản,Real Estate Sector Index,Sector Indices,17,166.0
14,VNFIN,VNFIN,Tài chính,Financials Sector Index,Sector Indices,18,138.0
15,VNMAT,VNMAT,Nguyên vật liệu,Materials Sector Index,Sector Indices,19,143.0
16,VNDIAMOND,VNDIAMOND,Chỉ số các cổ phiếu có triển vọng lớn của doan...,Vietnam Diamond Index,Investment Indices,2,NaN
17,VNFINLEAD,VNFINLEAD,Chỉ số của các cổ phiếu thuộc nhóm ngành tài c...,Vietnam Leading Financial Index,Investment Indices,3,NaN
18,VNFINSELECT,VNFINSELECT,Chỉ số của các cổ phiếu đại diện cho ngành tài...,Vietnam Financial Select Sector Index,Investment Indices,4,NaN
19,VNX50,VNX50,50 cổ phiếu vốn hóa lớn nhất trên toàn bộ thị ...,VNX50 Index,VNX Indices,4,NaN
20,VNXALL,VNXALL,Tất cả cổ phiếu trên toàn bộ thị trường HOSE v...,VNX All Index,VNX Indices,1,NaN

## Quote: Giá chứng khoán

### KBS

In [ ]:
from vnstock import Quote
quote = Quote(symbol='ACB', source='KBS')

#### Giá lịch sử

##### Cổ phiếu

In [ ]:
# Lấy báo cáo lùi N ngày so với hiện tại (bao gồm cả ngày hiện tại)
df = quote.history(length='90', interval='d')
df

                  time     open     high      low    close    volume
0  2025-10-20 07:00:00  25600.0  25650.0  24600.0  24800.0  32231800
1  2025-10-21 07:00:00  24850.0  25300.0  24850.0  25000.0  19371400
2  2025-10-22 07:00:00  25200.0  25300.0  24650.0  25100.0  15620500
3  2025-10-23 07:00:00  25100.0  25200.0  24950.0  24950.0   8751200
4  2025-10-24 07:00:00  24950.0  25300.0  24800.0  25000.0  11724500
..                 ...      ...      ...      ...      ...       ...
58 2026-01-12 07:00:00  24650.0  25500.0  24650.0  25500.0  22302500
59 2026-01-13 07:00:00  25700.0  25800.0  24900.0  24900.0  24138300
60 2026-01-14 07:00:00  25000.0  25150.0  24500.0  24650.0  19456100
61 2026-01-15 07:00:00  24850.0  24900.0  24550.0  24900.0  14169900
62 2026-01-16 07:00:00  25000.0  25100.0  24650.0  24850.0  10941400

[63 rows x 6 columns]

In [ ]:
# Lấy báo cáo theo 1 dải thời gian cố định
df = quote.history(start='2024-01-01', end='2025-03-19', interval='d')
df

                   time      open      high       low     close    volume
0   2024-01-02 07:00:00  16813.64  17375.27  16813.64  17164.66  13883500
1   2024-01-03 07:00:00  17199.76  17550.78  17024.25  17550.78   9803400
2   2024-01-04 07:00:00  17691.18  18007.10  17620.98  17761.38  23587800
3   2024-01-05 07:00:00  17761.38  17866.69  17585.88  17866.69   9272100
4   2024-01-08 07:00:00  18042.20  18077.30  17691.18  17796.49  12389600
..                  ...       ...       ...       ...       ...       ...
295 2025-03-13 07:00:00  22018.48  22102.04  21809.58  21809.58   8885500
296 2025-03-14 07:00:00  21893.14  21893.14  21642.45  21726.02  11548600
297 2025-03-17 07:00:00  21809.58  21934.92  21726.02  21893.14   5664400
298 2025-03-18 07:00:00  21976.70  22185.60  21934.92  21976.70   6008500
299 2025-03-19 07:00:00  21976.70  21976.70  21767.80  21893.14   7913600

[300 rows x 6 columns]

##### Hợp đồng tương lai

In [ ]:
quote.history(symbol='VN30F1M', length=90, interval='d')

                  time     open     high      low    close    volume
0  2025-10-20 07:00:00  25600.0  25650.0  24600.0  24800.0  32231800
1  2025-10-21 07:00:00  24850.0  25300.0  24850.0  25000.0  19371400
2  2025-10-22 07:00:00  25200.0  25300.0  24650.0  25100.0  15620500
3  2025-10-23 07:00:00  25100.0  25200.0  24950.0  24950.0   8751200
4  2025-10-24 07:00:00  24950.0  25300.0  24800.0  25000.0  11724500
..                 ...      ...      ...      ...      ...       ...
58 2026-01-12 07:00:00  24650.0  25500.0  24650.0  25500.0  22302500
59 2026-01-13 07:00:00  25700.0  25800.0  24900.0  24900.0  24138300
60 2026-01-14 07:00:00  25000.0  25150.0  24500.0  24650.0  19456100
61 2026-01-15 07:00:00  24850.0  24900.0  24550.0  24900.0  14169900
62 2026-01-16 07:00:00  25000.0  25100.0  24650.0  24850.0  10941400

[63 rows x 6 columns]

In [ ]:
quote.history(symbol='41I1G2000', length=90, interval='d')

                  time     open     high      low    close    volume
0  2025-10-20 07:00:00  25600.0  25650.0  24600.0  24800.0  32231800
1  2025-10-21 07:00:00  24850.0  25300.0  24850.0  25000.0  19371400
2  2025-10-22 07:00:00  25200.0  25300.0  24650.0  25100.0  15620500
3  2025-10-23 07:00:00  25100.0  25200.0  24950.0  24950.0   8751200
4  2025-10-24 07:00:00  24950.0  25300.0  24800.0  25000.0  11724500
..                 ...      ...      ...      ...      ...       ...
58 2026-01-12 07:00:00  24650.0  25500.0  24650.0  25500.0  22302500
59 2026-01-13 07:00:00  25700.0  25800.0  24900.0  24900.0  24138300
60 2026-01-14 07:00:00  25000.0  25150.0  24500.0  24650.0  19456100
61 2026-01-15 07:00:00  24850.0  24900.0  24550.0  24900.0  14169900
62 2026-01-16 07:00:00  25000.0  25100.0  24650.0  24850.0  10941400

[63 rows x 6 columns]

##### Chỉ số

In [ ]:
quote.history(symbol='VNINDEX', length=90, interval='d')

                  time     open     high      low    close    volume
0  2025-10-20 07:00:00  25600.0  25650.0  24600.0  24800.0  32231800
1  2025-10-21 07:00:00  24850.0  25300.0  24850.0  25000.0  19371400
2  2025-10-22 07:00:00  25200.0  25300.0  24650.0  25100.0  15620500
3  2025-10-23 07:00:00  25100.0  25200.0  24950.0  24950.0   8751200
4  2025-10-24 07:00:00  24950.0  25300.0  24800.0  25000.0  11724500
..                 ...      ...      ...      ...      ...       ...
58 2026-01-12 07:00:00  24650.0  25500.0  24650.0  25500.0  22302500
59 2026-01-13 07:00:00  25700.0  25800.0  24900.0  24900.0  24138300
60 2026-01-14 07:00:00  25000.0  25150.0  24500.0  24650.0  19456100
61 2026-01-15 07:00:00  24850.0  24900.0  24550.0  24900.0  14169900
62 2026-01-16 07:00:00  25000.0  25100.0  24650.0  24850.0  10941400

[63 rows x 6 columns]

In [ ]:
quote.history(symbol='HNXINDEX', length=90, interval='d')

                  time     open     high      low    close    volume
0  2025-10-20 07:00:00  25600.0  25650.0  24600.0  24800.0  32231800
1  2025-10-21 07:00:00  24850.0  25300.0  24850.0  25000.0  19371400
2  2025-10-22 07:00:00  25200.0  25300.0  24650.0  25100.0  15620500
3  2025-10-23 07:00:00  25100.0  25200.0  24950.0  24950.0   8751200
4  2025-10-24 07:00:00  24950.0  25300.0  24800.0  25000.0  11724500
..                 ...      ...      ...      ...      ...       ...
58 2026-01-12 07:00:00  24650.0  25500.0  24650.0  25500.0  22302500
59 2026-01-13 07:00:00  25700.0  25800.0  24900.0  24900.0  24138300
60 2026-01-14 07:00:00  25000.0  25150.0  24500.0  24650.0  19456100
61 2026-01-15 07:00:00  24850.0  24900.0  24550.0  24900.0  14169900
62 2026-01-16 07:00:00  25000.0  25100.0  24650.0  24850.0  10941400

[63 rows x 6 columns]

In [ ]:
quote.history(symbol='UPCOMINDEX', length=90, interval='d')

📋 Kết nối tài khoản Google Drive để lưu các thiết lập của dự án.
Dữ liệu phiên làm việc với Colab của bạn sẽ bị xóa nếu không lưu trữ vào Google Drive.

                  time     open     high      low    close    volume
0  2025-10-20 07:00:00  25600.0  25650.0  24600.0  24800.0  32231800
1  2025-10-21 07:00:00  24850.0  25300.0  24850.0  25000.0  19371400
2  2025-10-22 07:00:00  25200.0  25300.0  24650.0  25100.0  15620500
3  2025-10-23 07:00:00  25100.0  25200.0  24950.0  24950.0   8751200
4  2025-10-24 07:00:00  24950.0  25300.0  24800.0  25000.0  11724500
..                 ...      ...      ...      ...      ...       ...
58 2026-01-12 07:00:00  24650.0  25500.0  24650.0  25500.0  22302500
59 2026-01-13 07:00:00  25700.0  25800.0  24900.0  24900.0  24138300
60 2026-01-14 07:00:00  25000.0  25150.0  24500.0  24650.0  19456100
61 2026-01-15 07:00:00  24850.0  24900.0  24550.0  24900.0  14169900
62 2026-01-16 07:00:00  25000.0  25100.0  24650.0  24850.0  10941400

[63 rows x 6 columns]

##### Chứng quyền

In [ ]:
quote.history(symbol='CFPT2314', length=90, interval='d')

                  time     open     high      low    close    volume
0  2025-10-20 07:00:00  25600.0  25650.0  24600.0  24800.0  32231800
1  2025-10-21 07:00:00  24850.0  25300.0  24850.0  25000.0  19371400
2  2025-10-22 07:00:00  25200.0  25300.0  24650.0  25100.0  15620500
3  2025-10-23 07:00:00  25100.0  25200.0  24950.0  24950.0   8751200
4  2025-10-24 07:00:00  24950.0  25300.0  24800.0  25000.0  11724500
..                 ...      ...      ...      ...      ...       ...
58 2026-01-12 07:00:00  24650.0  25500.0  24650.0  25500.0  22302500
59 2026-01-13 07:00:00  25700.0  25800.0  24900.0  24900.0  24138300
60 2026-01-14 07:00:00  25000.0  25150.0  24500.0  24650.0  19456100
61 2026-01-15 07:00:00  24850.0  24900.0  24550.0  24900.0  14169900
62 2026-01-16 07:00:00  25000.0  25100.0  24650.0  24850.0  10941400

[63 rows x 6 columns]

##### Trái phiếu niêm yết

In [ ]:
quote.history(symbol='CII424002', length=90, interval='d')

                  time     open     high      low    close    volume
0  2025-10-20 07:00:00  25600.0  25650.0  24600.0  24800.0  32231800
1  2025-10-21 07:00:00  24850.0  25300.0  24850.0  25000.0  19371400
2  2025-10-22 07:00:00  25200.0  25300.0  24650.0  25100.0  15620500
3  2025-10-23 07:00:00  25100.0  25200.0  24950.0  24950.0   8751200
4  2025-10-24 07:00:00  24950.0  25300.0  24800.0  25000.0  11724500
..                 ...      ...      ...      ...      ...       ...
58 2026-01-12 07:00:00  24650.0  25500.0  24650.0  25500.0  22302500
59 2026-01-13 07:00:00  25700.0  25800.0  24900.0  24900.0  24138300
60 2026-01-14 07:00:00  25000.0  25150.0  24500.0  24650.0  19456100
61 2026-01-15 07:00:00  24850.0  24900.0  24550.0  24900.0  14169900
62 2026-01-16 07:00:00  25000.0  25100.0  24650.0  24850.0  10941400

[63 rows x 6 columns]

#### Intraday: dữ liệu khớp lệnh

In [ ]:
# Dữ liệu khớp lệnh trong ngày giao dịch realtime hoặc ngày gần nhất (ngoài giờ giao dịch)
quote.intraday(symbol='ACB', page_size=10_000, show_log=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,time,price,volume,match_type,id
2438,2026-01-16 09:15:03,25000.0,106700,ato,2026-01-16_091503_250000_106700
2435,2026-01-16 09:15:13,24950.0,1000,sell,2026-01-16_091513_249500_1000
2437,2026-01-16 09:15:13,25000.0,600,buy,2026-01-16_091513_250000_600
2436,2026-01-16 09:15:13,24950.0,100,sell,2026-01-16_091513_249500_100
2434,2026-01-16 09:15:14,25000.0,300,buy,2026-01-16_091514_250000_300
...,...,...,...,...,...
4,2026-01-16 14:29:38,24700.0,6600,sell,2026-01-16_142938_247000_6600
3,2026-01-16 14:29:39,24700.0,20000,sell,2026-01-16_142939_247000_20000
2,2026-01-16 14:29:44,24750.0,2000,buy,2026-01-16_142944_247500_2000
1,2026-01-16 14:45:04,24850.0,486600,atc,2026-01-16_144504_248500_486600
0,2026-01-16 14:45:04,24850.0,419300,,2026-01-16_144504_248500_419300

### VCI

In [ ]:
from vnstock import Quote
quote = Quote(symbol='ACB', source='VCI')

#### Giá lịch sử

##### Cổ phiếu

In [ ]:
# Khung thời gian ngày: 1D hay d cho interval
df = quote.history(start='2024-01-01', end='2025-11-10', interval='d')
df

          time   open   high    low  close    volume
0   2023-11-23  15.93  15.97  15.58  15.58   5185123
1   2023-11-24  15.65  15.65  15.30  15.48   7901317
2   2023-11-27  15.48  15.51  15.33  15.33   3262375
3   2023-11-28  15.37  15.51  15.23  15.37   4189072
4   2023-11-29  15.44  15.69  15.44  15.48   4831388
..         ...    ...    ...    ...    ...       ...
483 2025-11-03  25.40  25.90  25.30  25.45  13864900
484 2025-11-04  25.45  26.10  25.40  26.00  17972000
485 2025-11-05  25.80  25.90  25.55  25.60   6212200
486 2025-11-06  25.55  25.70  25.30  25.30   6525200
487 2025-11-07  25.25  25.30  24.85  24.90  12107200

[488 rows x 6 columns]

In [ ]:
# Khung thời gian phút: 1m hoặc m cho interval
df = quote.history(start='2025-01-02', end='2025-11-10', interval='1m')
df

                     time   open   high    low  close  volume
0     2024-04-09 09:39:00  19.02  19.05  18.98  19.02   17600
1     2024-04-09 09:40:00  19.02  19.05  19.02  19.02    9600
2     2024-04-09 09:41:00  19.02  19.02  18.98  19.02    5500
3     2024-04-09 09:42:00  19.02  19.02  19.02  19.02     600
4     2024-04-09 09:43:00  19.02  19.05  19.02  19.05   19100
...                   ...    ...    ...    ...    ...     ...
87356 2025-11-07 14:26:00  25.00  25.10  25.00  25.05   83800
87357 2025-11-07 14:27:00  25.05  25.10  24.90  24.95  239200
87358 2025-11-07 14:28:00  25.00  25.00  24.90  24.95   90600
87359 2025-11-07 14:29:00  24.90  24.95  24.90  24.90  109600
87360 2025-11-07 14:45:00  24.90  24.90  24.90  24.90  700800

[87361 rows x 6 columns]

In [ ]:
# Khung thời gian giờ: 1H hoặc h cho interval
df = quote.history(start='2025-01-02', end='2025-11-10', interval='h')
df

                    time   open   high    low  close   volume
0    2024-08-06 13:00:00  19.51  19.72  19.51  19.68  1873000
1    2024-08-06 14:00:00  19.68  19.76  19.63  19.63  1406000
2    2024-08-07 10:00:00  19.55  19.59  19.51  19.51  1370300
3    2024-08-07 11:00:00  19.51  19.55  19.51  19.51   225900
4    2024-08-07 13:00:00  19.51  19.63  19.51  19.63   944700
...                  ...    ...    ...    ...    ...      ...
1452 2025-11-07 09:00:00  25.25  25.30  25.15  25.20  1277500
1453 2025-11-07 10:00:00  25.15  25.20  25.05  25.15  1918500
1454 2025-11-07 11:00:00  25.15  25.20  25.10  25.15   574900
1455 2025-11-07 13:00:00  25.15  25.30  25.05  25.10  2218800
1456 2025-11-07 14:00:00  25.10  25.15  24.85  24.90  6117500

[1457 rows x 6 columns]

##### Hợp đồng tương lai

In [ ]:
quote.history(symbol='VN30F1M', start='2024-01-02', end='2025-11-10', interval='1D')

          time   open   high    low  close    volume
0   2023-11-24  15.65  15.65  15.30  15.48   7901317
1   2023-11-27  15.48  15.51  15.33  15.33   3262375
2   2023-11-28  15.37  15.51  15.23  15.37   4189072
3   2023-11-29  15.44  15.69  15.44  15.48   4831388
4   2023-11-30  15.48  15.65  15.40  15.40   5245608
..         ...    ...    ...    ...    ...       ...
482 2025-11-03  25.40  25.90  25.30  25.45  13864900
483 2025-11-04  25.45  26.10  25.40  26.00  17972000
484 2025-11-05  25.80  25.90  25.55  25.60   6212200
485 2025-11-06  25.55  25.70  25.30  25.30   6525200
486 2025-11-07  25.25  25.30  24.85  24.90  12107200

[487 rows x 6 columns]

In [ ]:
quote.history(symbol='41I1FB000', start='2025-01-02', end='2025-11-10', interval='1m')

                     time   open   high    low  close  volume
0     2024-04-09 09:39:00  19.02  19.05  18.98  19.02   17600
1     2024-04-09 09:40:00  19.02  19.05  19.02  19.02    9600
2     2024-04-09 09:41:00  19.02  19.02  18.98  19.02    5500
3     2024-04-09 09:42:00  19.02  19.02  19.02  19.02     600
4     2024-04-09 09:43:00  19.02  19.05  19.02  19.05   19100
...                   ...    ...    ...    ...    ...     ...
87356 2025-11-07 14:26:00  25.00  25.10  25.00  25.05   83800
87357 2025-11-07 14:27:00  25.05  25.10  24.90  24.95  239200
87358 2025-11-07 14:28:00  25.00  25.00  24.90  24.95   90600
87359 2025-11-07 14:29:00  24.90  24.95  24.90  24.90  109600
87360 2025-11-07 14:45:00  24.90  24.90  24.90  24.90  700800

[87361 rows x 6 columns]

In [ ]:
quote.history(symbol='VN30F2511', start='2025-01-02', end='2025-11-10', interval='1D')

          time   open   high    low  close    volume
0   2024-12-12  21.22  21.31  21.10  21.14   5867353
1   2024-12-13  21.14  21.14  20.97  21.01   6044475
2   2024-12-16  21.01  21.10  20.93  21.01   5165719
3   2024-12-17  21.10  21.10  20.93  21.05   3331723
4   2024-12-18  21.10  21.10  20.97  21.01   3385137
..         ...    ...    ...    ...    ...       ...
220 2025-11-03  25.40  25.90  25.30  25.45  13864900
221 2025-11-04  25.45  26.10  25.40  26.00  17972000
222 2025-11-05  25.80  25.90  25.55  25.60   6212200
223 2025-11-06  25.55  25.70  25.30  25.30   6525200
224 2025-11-07  25.25  25.30  24.85  24.90  12107200

[225 rows x 6 columns]

##### Chỉ số

In [ ]:
quote.history(symbol='VNINDEX', start='2024-01-02', end='2025-11-10', interval='1D')

          time   open   high    low  close    volume
0   2023-11-24  15.65  15.65  15.30  15.48   7901317
1   2023-11-27  15.48  15.51  15.33  15.33   3262375
2   2023-11-28  15.37  15.51  15.23  15.37   4189072
3   2023-11-29  15.44  15.69  15.44  15.48   4831388
4   2023-11-30  15.48  15.65  15.40  15.40   5245608
..         ...    ...    ...    ...    ...       ...
482 2025-11-03  25.40  25.90  25.30  25.45  13864900
483 2025-11-04  25.45  26.10  25.40  26.00  17972000
484 2025-11-05  25.80  25.90  25.55  25.60   6212200
485 2025-11-06  25.55  25.70  25.30  25.30   6525200
486 2025-11-07  25.25  25.30  24.85  24.90  12107200

[487 rows x 6 columns]

In [ ]:
quote.history(symbol='HNXINDEX', start='2024-01-02', end='2025-11-10', interval='1D')

          time   open   high    low  close    volume
0   2023-11-24  15.65  15.65  15.30  15.48   7901317
1   2023-11-27  15.48  15.51  15.33  15.33   3262375
2   2023-11-28  15.37  15.51  15.23  15.37   4189072
3   2023-11-29  15.44  15.69  15.44  15.48   4831388
4   2023-11-30  15.48  15.65  15.40  15.40   5245608
..         ...    ...    ...    ...    ...       ...
482 2025-11-03  25.40  25.90  25.30  25.45  13864900
483 2025-11-04  25.45  26.10  25.40  26.00  17972000
484 2025-11-05  25.80  25.90  25.55  25.60   6212200
485 2025-11-06  25.55  25.70  25.30  25.30   6525200
486 2025-11-07  25.25  25.30  24.85  24.90  12107200

[487 rows x 6 columns]

In [ ]:
quote.history(symbol='UPCOMINDEX', start='2024-01-02', end='2025-11-10', interval='1D')

          time   open   high    low  close    volume
0   2023-11-24  15.65  15.65  15.30  15.48   7901317
1   2023-11-27  15.48  15.51  15.33  15.33   3262375
2   2023-11-28  15.37  15.51  15.23  15.37   4189072
3   2023-11-29  15.44  15.69  15.44  15.48   4831388
4   2023-11-30  15.48  15.65  15.40  15.40   5245608
..         ...    ...    ...    ...    ...       ...
482 2025-11-03  25.40  25.90  25.30  25.45  13864900
483 2025-11-04  25.45  26.10  25.40  26.00  17972000
484 2025-11-05  25.80  25.90  25.55  25.60   6212200
485 2025-11-06  25.55  25.70  25.30  25.30   6525200
486 2025-11-07  25.25  25.30  24.85  24.90  12107200

[487 rows x 6 columns]

##### Chứng quyền

In [ ]:
quote.history(symbol='CFPT2314', start='2024-01-02', end='2025-11-10', interval='1D')

          time   open   high    low  close    volume
0   2023-11-24  15.65  15.65  15.30  15.48   7901317
1   2023-11-27  15.48  15.51  15.33  15.33   3262375
2   2023-11-28  15.37  15.51  15.23  15.37   4189072
3   2023-11-29  15.44  15.69  15.44  15.48   4831388
4   2023-11-30  15.48  15.65  15.40  15.40   5245608
..         ...    ...    ...    ...    ...       ...
482 2025-11-03  25.40  25.90  25.30  25.45  13864900
483 2025-11-04  25.45  26.10  25.40  26.00  17972000
484 2025-11-05  25.80  25.90  25.55  25.60   6212200
485 2025-11-06  25.55  25.70  25.30  25.30   6525200
486 2025-11-07  25.25  25.30  24.85  24.90  12107200

[487 rows x 6 columns]

##### Trái phiếu niêm yết

In [ ]:
quote.history(symbol='CII424002', start='2024-01-02', end='2025-11-10', interval='1D')

          time   open   high    low  close    volume
0   2023-11-24  15.65  15.65  15.30  15.48   7901317
1   2023-11-27  15.48  15.51  15.33  15.33   3262375
2   2023-11-28  15.37  15.51  15.23  15.37   4189072
3   2023-11-29  15.44  15.69  15.44  15.48   4831388
4   2023-11-30  15.48  15.65  15.40  15.40   5245608
..         ...    ...    ...    ...    ...       ...
482 2025-11-03  25.40  25.90  25.30  25.45  13864900
483 2025-11-04  25.45  26.10  25.40  26.00  17972000
484 2025-11-05  25.80  25.90  25.55  25.60   6212200
485 2025-11-06  25.55  25.70  25.30  25.30   6525200
486 2025-11-07  25.25  25.30  24.85  24.90  12107200

[487 rows x 6 columns]

#### Intraday: dữ liệu khớp lệnh

In [ ]:
# Dữ liệu khớp lệnh trong ngày giao dịch realtime hoặc ngày gần nhất (ngoài giờ giao dịch)
quote.intraday(symbol='ACB', page_size=10_000, show_log=False)

                          time  price  volume match_type         id
0    2025-11-07 09:15:00+07:00  25.25     100       Sell  393407018
1    2025-11-07 09:15:00+07:00  25.25     100       Sell  393407060
2    2025-11-07 09:15:00+07:00  25.25     300       Sell  393407061
3    2025-11-07 09:15:00+07:00  25.25    1500       Sell  393407062
4    2025-11-07 09:15:00+07:00  25.25     100       Sell  393407063
...                        ...    ...     ...        ...        ...
6682 2025-11-07 14:45:00+07:00  24.90    5000        Buy  394037019
6683 2025-11-07 14:45:00+07:00  24.90     200        Buy  394037018
6684 2025-11-07 14:45:00+07:00  24.90     100        Buy  394037017
6685 2025-11-07 14:45:00+07:00  24.90     200        Buy  394037033
6686 2025-11-07 14:45:00+07:00  24.90     100        Buy  394037576

[6687 rows x 5 columns]

## Trading: Giao dịch

### Bảng giá

#### KBS

In [ ]:
from vnstock import Trading
trading = Trading(source='KBS')

In [ ]:
trading.price_board(['ACB'])

,symbol,time,exchange,ceiling_price,floor_price,reference_price,open_price,high_price,low_price,close_price,...,bid_price_3,bid_vol_3,ask_price_1,ask_vol_1,ask_price_2,ask_vol_2,ask_price_3,ask_vol_3,foreign_buy_volume,foreign_sell_volume
0,ACB,1768552380433,HOSE,26600,23200,24900,25000,25100,24650,24850,...,24700,259900,24850.0,176300,24900,1212500,24950,128700,1509500,77431639

In [ ]:
trading.price_board(['VCB','ACB','TCB','BID']).T # Bỏ .T để xoay trở lại đúng kiểu hiển thị bảng giá

,0,1,2,3
symbol,VCB,ACB,TCB,BID
time,1768552349519,1768552380433,1768550700978,1768552382835
exchange,HOSE,HOSE,HOSE,HOSE
ceiling_price,76900,26600,38050,54200
floor_price,66900,23200,33150,47200
reference_price,71900,24900,35600,50700
open_price,73000,25000,35650,51000
high_price,76000,25100,36350,54200
low_price,72000,24650,35600,50400
close_price,73000,24850,35800,51100
average_price,73392,24788,35953,52021
total_trades,13426500,10941400,9580800,13973800
total_value,985393610000,271211480000,344454670000,726931030000
price_change,1100,-50,200,400
percent_change,1.529903,-0.200803,0.561798,0.788955
bid_price_1,72900.0,24800.0,35800.0,51100.0
bid_vol_1,100,900,53700,33100
bid_price_2,72800,24750,35750,51000
bid_vol_2,100,4500,63000,327700
bid_price_3,72700,24700,35700,50900
bid_vol_3,170100,259900,98800,14200
ask_price_1,73000.0,24850.0,35850.0,51200.0
ask_vol_1,57000,176300,1300,1900
ask_price_2,73100,24900,35900,51300
ask_vol_2,4000,1212500,13800,6000
ask_price_3,73200,24950,35950,51400
ask_vol_3,36900,128700,97700,8300
foreign_buy_volume,2540007,1509500,0,2334772
foreign_sell_volume,709119811,77431639,0,888147307

#### VCI

In [ ]:
from vnstock import Trading
trading = Trading(source='VCI')

In [ ]:
trading.price_board(['ACB'])

  listing                                                                  \
   symbol ceiling  floor ref_price stock_type exchange     trading_status
0     ACB   27050  23550     25300      STOCK      HSX  TRADING_ACTIVATED

                                                            ...     bid_ask  \
  trading_status_code trading_status_group security_status  ... bid_2_price
0                  20                    2               N  ...       24800

                                                                              \
  bid_2_volume bid_3_price bid_3_volume ask_1_price ask_1_volume ask_2_price
0       521900       24750       111900       24900        12200       24950


  ask_2_volume ask_3_price ask_3_volume
0        20200       25000        73300

[1 rows x 70 columns]

In [ ]:
trading.price_board(['VCB','ACB','TCB','BID']) # Bỏ .T để xoay trở lại đúng kiểu hiển thị bảng giá

  listing                                                                  \
   symbol ceiling  floor ref_price stock_type exchange     trading_status
0     VCB   64500  56100     60300      STOCK      HSX  TRADING_ACTIVATED
1     ACB   27050  23550     25300      STOCK      HSX  TRADING_ACTIVATED
2     TCB   35950  31250     33600      STOCK      HSX  TRADING_ACTIVATED
3     BID   41150  35850     38500      STOCK      HSX  TRADING_ACTIVATED

                                                            ...     bid_ask  \
  trading_status_code trading_status_group security_status  ... bid_2_price
0                  20                    2               N  ...       59200
1                  20                    2               N  ...       24800
2                  20                    2               N  ...       32950
3                  20                    2               N  ...       37450

                                                                              \
  bid_2_volume bid_3_price bid_3_volume ask_1_price ask_1_volume ask_2_price
0        25700       59100       118300       59400         2800       59500
1       521900       24750       111900       24900        12200       24950
2       174400       32900        87200       33050        48600       33100
3        32600       37400        24900       37550          800       37600


  ask_2_volume ask_3_price ask_3_volume
0          300       59600         9000
1        20200       25000        73300
2        21000       33150        10500
3        13900       37650         7900

[4 rows x 70 columns]

## Company: Thông tin công ty

### KBS

> Đã bổ sung nguồn dữ liệu từ VCI từ bản Vnstock 3.4.0

In [ ]:
from vnstock import Company
company = Company(symbol='ACB', source='KBS')

Loại bỏ đoạn mã `.head()` để xem toàn bộ dữ liệu thay vì chỉ lấy 5 dòng đầu tiên.

#### Hồ sơ

In [ ]:
company.overview()

,business_model,symbol,founded_date,charter_capital,number_of_employees,listing_date,par_value,exchange,listing_price,listed_volume,...,phone,fax,email,website,branches,history,free_float_percentage,free_float,outstanding_shares,as_of_date
0,"\n- Huy động vốn ngắn hạn, trung hạn và dài hạ...",ACB,24/04/1993,51367,13290,09/12/2020,10000,HOSE,26400,5137,...,(84.28) 3833 4085 - 3839 5179,(84.28) 3839 9885,acb@acb.com.vn,https://www.acb.com.vn,"-Tại TP. Hồ Chí Minh: Sở giao dịch, 25 chi nhá...",\n- Ngày 24/04/1993: Ngân hàng Thương mại Cổ p...,51366565990000,10000,5136656599,2024-12-31T00:00:00

#### Tỷ lệ sở hữu

In [ ]:
company.ownership()

           owner_type  ownership_percentage  shares_owned          update_date
0  Cá nhân trong nước                 47.77    2133712059  2024-12-31T00:00:00
1  Tổ chức trong nước                 22.23     992953362  2024-12-31T00:00:00
2  Cá nhân nước ngoài                  0.03       1130130  2024-12-31T00:00:00
3  Tổ chức nước ngoài                 29.97    1338862361  2024-12-31T00:00:00

#### Cổ đông

In [ ]:
company.shareholders()

,name,update_date,shares_owned,ownership_percentage
0,Trần Hùng Huy,2025-06-30T00:00:00,176021482,3.43
1,"SMALLCAP World Fund, Inc",2024-07-30T00:00:00,112118905,2.51
2,Boardwalk South Limited,2024-07-30T00:00:00,82268294,1.84
3,CTCP Đầu tư Thương mại Giang Sen,2025-06-30T00:00:00,92341027,1.80
4,VOF PE Holding 5 Limited,2024-07-30T00:00:00,76619537,1.72
5,Công ty TNHH Bảo hiểm Nhân thọ Prudiential Việ...,2024-07-30T00:00:00,69465590,1.56
6,Nguyễn Thiên Hương Jenny,2025-04-29T00:00:00,63232810,1.42
7,CTCP Làng giáo dục quốc tế Thiên Hương,2024-09-10T00:00:00,58575494,1.31
8,CTCP Đầu tư Thương mại Bách Thanh,2025-06-30T00:00:00,64287678,1.25
9,Đặng Thu Thủy,2025-06-30T00:00:00,61352541,1.19
10,Nguyễn Đức Hiếu Johnny,2025-04-29T00:00:00,51017819,1.14
11,Đặng Thu Hà,2025-06-30T00:00:00,53071816,1.03
12,Empoyees Provident Fund Board,2025-05-21T00:00:00,45600446,1.02

#### Công ty con

In [ ]:
company.subsidiaries()

,update_date,name,charter_capital,ownership_percent,currency,type
0,2024-12-31T00:00:00,Công ty TNHH Chứng khoán ACB,7000000000000,100,VND,công ty con
1,2024-12-31T00:00:00,Công ty TNHH MTV Cho thuê tài chính ACB (ACBL),500000000000,100,VND,công ty con
2,2024-12-31T00:00:00,Công ty TNHH MTV Quản lý Quỹ ACB,50000000000,100,VND,công ty con
3,2024-12-31T00:00:00,Công ty TNHH Quản lý nợ và Khai thác tài sản A...,5000000000,100,VND,công ty con

#### Công ty liên kết

In [ ]:
# Phương thức này không có trong nguồn TCBS
company.affiliate()

Empty DataFrame
Columns: [update_date, name, charter_capital, ownership_percent, currency, type]
Index: []

#### Lãnh đạo

In [ ]:
company.officers(filter_by='working').head() # filter_by='all' hoặc 'working' hoặc 'resigned'

,from_date,position,name,position_en,owner_code
0,2002,CTHĐQT,Ông Trần Hùng Huy,CTHĐQT (Chairman of BOD),CTHĐQT
1,2012,Phó CTHĐQT,Ông Nguyễn Thành Long,Phó CTHĐQT (Vice Chairman of BOD),Phó CTHĐQT
2,2018,TVHĐQT,Ông Hiep Van Vo,TVHĐQT (Member of BOD),TVHĐQT
3,TV Độc lập,TVHĐQT,Ông Trịnh Bảo Quốc,TVHĐQT (Member of BOD),TVHĐQT
4,2012,TVHĐQT,Bà Đinh Thị Hoa,TVHĐQT (Member of BOD),TVHĐQT

#### Lịch sử tăng vốn

In [ ]:
company.capital_history()

Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.

         date  charter_capital currency
0  2025-06-27   51366565990000      VND
1  2024-04-09   44666579120000      VND
2  2023-06-26   38840503580000      VND
3  2022-07-04   33774350940000      VND
4  2021-07-02   27019480750000      VND
5  2020-10-19   21615584600000      VND
6  2019-11-15   16627372770000      VND
7         NaT   12885877380000      VND
8  2017-03-09   10273238960000      VND
9         NaT    9376965060000      VND
10 2009-11-27    7814137550000      VND
11 2009-09-10    7705743780000      VND
12 2008-12-15    6355812780000      VND
13 2008-10-29    4651615940000      VND
14 2008-10-07    3180082960000      VND
15 2007-12-12    2630059960000      VND
16 2007-05-31    2530106520000      VND
17 2006-03-09    1100046560000      VND
18 2004-12-31     481138000000      VND

#### Tin tức

In [ ]:
company.news().head(3)

,head,article_id,title,publish_time,url
0,Giai đoạn tới không phải thời kỳ tăng trưởng d...,1381606,Doanh nghiệp cần chuẩn bị cho môi trường biến ...,2025-12-16T16:17:32.593,/2025/12/doanh-nghiep-can-chuan-bi-cho-moi-tru...

#### Sự kiện

In [ ]:
company.events()

Empty DataFrame
Columns: []
Index: []

#### Giao dịch nội bộ

In [ ]:
company.insider_trading()

Empty DataFrame
Columns: []
Index: []

### VCI

> Đã bổ sung nguồn dữ liệu từ VCI từ bản Vnstock 3.2.0

In [ ]:
from vnstock import Company
company = Company(symbol='ACB', source='VCI')

Loại bỏ đoạn mã `.head()` để xem toàn bộ dữ liệu thay vì chỉ lấy 5 dòng đầu tiên.

#### Hồ sơ

In [ ]:
company.overview()

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

,symbol,id,issue_share,history,company_profile,icb_name3,icb_name2,icb_name4,financial_ratio_issue_share,charter_capital
0,ACB,67505,5136656599,- Ngày 24/04/1993: Ngân hàng Thương mại Cổ ph...,Ngân hàng Thương mại Cổ phần Á Châu (ACB) được...,Ngân hàng,Ngân hàng,Ngân hàng,5136656599,51366565990000

#### Cổ đông

In [ ]:
company.shareholders()

,id,share_holder,quantity,share_own_percent,update_date
0,92044288,Vietnam Enterprise Investments Limited,212880184,0.054809,2024-09-13
1,92039097,Sather Gate Investments Limited,193907186,0.049900,2025-10-05
2,92020366,Estes Investments Limited,83010435,0.049900,2024-05-15
3,92036861,Phạm Thị Thu Hà,285000,0.049900,2016-05-20
4,92019944,Dragon Financial Holdings Limited,140770684,0.036243,2025-10-05
...,...,...,...,...,...
85,92038620,Quỹ Đầu tư Cổ phiếu Năng động Bảo Việt,22065,0.000013,2025-10-05
86,92018614,Đinh Thị Hoa,77280,0.000012,2025-10-05
87,92026583,Ngô Tấn Long,63442,0.000010,2025-10-29
88,92020200,Dương Thị Nguyệt,17975,0.000003,2025-10-29
89,92014452,Công ty Cổ phần Chứng khoán Thiên Việt,5285,0.000002,2025-10-05

#### Công ty con

In [ ]:
company.subsidiaries()

,id,sub_organ_code,ownership_percent,organ_name,type
0,26024573,ACBA,1,Công Ty TNHH Quản Lý Nợ Và Khai Thác Tài Sản N...,công ty con
1,26024574,ACBL,1,Công Ty TNHH Một Thành Viên Cho Thuê Tài Chính...,công ty con
2,26024575,ACBS,1,Công ty TNHH Chứng khoán ACB,công ty con
0,26024577,ACBD,None,CÔNG TY CỔ PHẦN DỊCH VỤ BẢO VỆ NGÂN HÀNG Á CHÂU,công ty liên kết
1,26024576,SGGS,None,Công ty Cổ phần Sài Gòn Kim hoàn ACB- SJC,công ty liên kết

#### Công ty liên kết

In [ ]:
# Phương thức này không có trong nguồn TCBS
company.affiliate()

,id,sub_organ_code,organ_name,ownership_percent
0,26024577,ACBD,CÔNG TY CỔ PHẦN DỊCH VỤ BẢO VỆ NGÂN HÀNG Á CHÂU,None
1,26024576,SGGS,Công ty Cổ phần Sài Gòn Kim hoàn ACB- SJC,None

#### Lãnh đạo

In [ ]:
company.officers(filter_by='working').head() # filter_by='all' hoặc 'working' hoặc 'resigned'

,id,officer_name,officer_position,position_short_name,update_date,officer_own_percent,quantity
0,6,Trần Hùng Huy,Chủ tịch Hội đồng Quản trị,Chủ tịch HĐQT,2025-08-12,0.0343,176021482
1,7,Đặng Thu Thủy,Thành viên Hội đồng Quản trị,TV HĐQT,2025-08-12,0.0119,61352541
2,17,Đặng Phú Vinh,Giám đốc khối,GĐ Khối,2025-08-12,0.0037,18922683
3,8,Đỗ Minh Toàn,Tổng Giám đốc,TGĐ,2025-08-12,0.0007,3683318
4,9,Nguyễn Thành Long,Phó Chủ tịch Hội đồng Quản trị,Phó Chủ tịch HĐQT,2025-08-12,0.0004,1894127

#### Tin tức

In [ ]:
company.news().head(3)

,id,news_title,news_sub_title,friendly_sub_title,news_image_url,news_source_link,created_at,public_date,updated_at,lang_code,news_id,news_short_content,news_full_content,close_price,ref_price,floor,ceiling,price_change_pct
0,8699409,ACB: Dự thảo Nghị quyết ĐHĐCĐ thành lập công t...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/acb-du-thao-nghi...,None,1761562938000,None,vi,11774312,Ngân hàng Thương mại Cổ phần Á Châu công bố Dự...,<p>Ngân hàng Thương mại Cổ phần Á Châu công bố...,25000,25000,23250,26750,0.0
1,8699410,ACB: Phiếu lấy ý kiến cổ đông bằng văn bản,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/acb-phieu-lay-y-...,None,1761562874000,None,vi,11774315,Ngân hàng Thương mại Cổ phần Á Châu công bố Ph...,<p>Ngân hàng Thương mại Cổ phần Á Châu công bố...,25000,25000,23250,26750,0.0
2,8699366,ACB: Tờ trình ĐHĐCĐ về việc thành lập công ty con,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/acb-to-trinh-dhd...,None,1761562827000,None,vi,11774248,Ngân hàng Thương mại Cổ phần Á Châu công bố Tờ...,<p>Ngân hàng Thương mại Cổ phần Á Châu công bố...,25000,25000,23250,26750,0.0

#### Sự kiện

In [ ]:
company.events().head(3)

,id,event_title,en__event_title,public_date,issue_date,source_url,event_list_code,ratio,value,record_date,exright_date,event_list_name,en__event_list_name
0,18139,Trả cổ tức bằng tiền mặt,,2015-05-05,2015-05-29,http://stoxvn.stox.vn/tin-tuc/250588/acb-1505-...,DIV,NaN,NaN,2015-05-19,2015-05-15,Trả cổ tức bằng tiền mặt,Cash Dividend
1,18153,ACB - Niêm yết bổ sung 106.101 cổ phiếu,"ACB - Lists additional 106,101 shares",2021-07-16,2022-04-26,http://fiinpro.com/News/Detail/8195547?lang=vi-VN,AIS,0.0,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
2,58604768,ACB - Niêm yết bổ sung 669.998.687 cổ phiếu,"ACB- Lists additional 669,998,687 shares",2025-06-27,2025-06-26,http://fiinpro.com/News/Detail/11613539?lang=v...,AIS,0.0,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing

#### Báo cáo phân tích

In [ ]:
company.reports()

,date,description,link,name
0,2025-10-23T00:00:00Z,1. Thanh tra Chính phủ về hoạt động phát hành ...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB – Không ghi nhận sai phạm trong phát hành ...
1,2025-10-22T00:00:00Z,Ngân hàng TMCP Á Châu (ACB) công bố KQKD 9 thá...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - Chất lượng tài sản tiếp tục cải thiện; s...
2,2025-08-25T00:00:00Z,"- Chúng tôi điều chỉnh tăng 9,5% giá mục tiêu ...",https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB [MUA +21,3%] - Định giá hấp dẫn; sẵn sàng ..."
3,2025-07-24T00:00:00Z,Ngân hàng TMCP Á Châu (ACB) công bố KQKD 6 thá...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - Chất lượng tài sản cải thiện đáng kể; NI...
4,2025-05-27T00:00:00Z,"- Chúng tôi điều chỉnh giảm 2,4% giá mục tiêu ...",https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB [MUA +32,3%] - NIM dự kiến sẽ phải chịu áp..."
5,2025-04-24T00:00:00Z,1. Tác động của Thuế quan đối với ACB: Tác độn...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - Kỳ vọng tín dụng tăng mạnh và NIM cải th...
6,2025-04-23T00:00:00Z,Ngân hàng TMCP Á Châu (ACB) công bố KQKD quý 1...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - Lợi nhuận thấp hơn kỳ vọng do NIM giảm -...
7,2025-04-08T00:00:00Z,Chúng tôi đã tham dự ĐHCĐ của Ngân hàng TMCP Á...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - Tăng trưởng tín dụng được kỳ vọng sẽ nằm...
8,2025-01-22T00:00:00Z,Ngân hàng Thương Mại Cổ Phần Á Châu (ACB) đã c...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - Tập trung vào tăng trưởng tín dụng hơn t...
9,2024-10-24T00:00:00Z,Ngân hàng TMCP Á Châu (ACB) công bố KQKD 9 thá...,https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB – NOII thấp hơn dự kiến, ảnh hưởng tiêu cự..."

#### Tình hình tài chính

In [ ]:
company.ratio_summary()

,symbol,year_report,length_report,update_date,revenue,revenue_growth,net_profit,net_profit_growth,ebit_margin,roe,...,rtq4,charter_capital_ratio,rtq10,dividend,ebitda,ebit,le,de,ccc,rtq17
0,ACB,2025,3,1761151439463,15049404000000,0.164628,4280589000000,0.105982,0,0.199167,...,0,1.779669,9.37624,0.040161,0,0,0,9.37624,None,0

#### Thống kê giao dịch

In [ ]:
company.trading_stats()

,symbol,exchange,ev,ceiling,floor,ref_price,open,match_price,close_price,price_change,...,high_price_1y,low_price_1y,pct_low_change_1y,pct_high_change_1y,foreign_volume,foreign_room,avg_match_volume_2w,foreign_holding_room,current_holding_ratio,max_holding_ratio
0,ACB,HOSE,127902749315100,27050,23550,25300,25250,24900,24900,-400,...,29500,17337,0.367088,-0.154499,4221400,1540996979,10571974,1513762055,0.294698,0.3

## Finance: Báo cáo tài chính

### KBS

In [ ]:
from vnstock import Finance
finance = Finance(symbol='ACB', source='KBS')

#### Bảng cân đối kế toán

In [ ]:
finance.balance_sheet(period='year')

,item,item_en,item_id,unit,levels,row_number,2024,2023,2022,2021
0,A. TÀI SẢN,ASSETS,assets,None,0,1,NaN,NaN,NaN,NaN
1,"I. Tiền mặt, vàng bạc, đá quý","I. Cash, gold and silver, precious stones","cash,_gold_and_silver,_precious_stones",None,1,2,5.696449e+09,6.909300e+09,8.460892e+09,7.509877e+09
2,II. Tiền gửi tại NHNN,II. Balances with the State Bank of Vietnam,balances_with_the_state_bank_of_vietnam,None,1,3,2.521975e+10,1.850481e+10,1.365753e+10,3.234957e+10
3,"III. Tiền, vàng gửi tại các TCTD khác và cho v...",III. Placements at and loans to other credit i...,placements_at_and_loans_to_other_credit_instit...,None,1,4,1.178823e+11,1.148739e+11,8.597131e+10,4.981878e+10
4,"1. Tiền, vàng gửi tại các TCTD khác",1. Placements at other credit institutions,placements_at_other_credit_institutions,None,2,5,1.177813e+11,1.146440e+11,8.233876e+10,4.371323e+10
...,...,...,...,...,...,...,...,...,...,...
72,4. Chênh lệch đánh giá lại tài sản,4. Assets revaluation differences,assets_revaluation_differences,None,2,73,NaN,NaN,NaN,NaN
73,5. Lợi nhuận chưa phân phối/Lỗ lũy kế,5. Undistributed earnings after tax/Accumulate...,undistributed_earnings_after_tax_accumulated_loss,None,2,74,2.373375e+10,2.028624e+10,1.517241e+10,1.044535e+10
74,6. Lợi ích cổ đông không kiểm soát,6. Minority's interest,minority's_interest,None,2,75,NaN,NaN,NaN,NaN
75,IX. Lợi ích của cổ đông thiểu số,IX. Minority interest,minority_interest,None,1,76,NaN,NaN,NaN,NaN
76,TỔNG NỢ PHẢI TRẢ VÀ VỐN CHỦ SỞ HỮU,TOTAL LIABILITIES AND OWNER'S EQUITY,total_liabilities_and_owner's_equity,None,0,77,8.640057e+11,7.187946e+11,6.078752e+11,5.277699e+11

In [ ]:
finance.balance_sheet(period='quarter')

,item,item_en,item_id,unit,levels,row_number,2025-Q3,2025-Q2,2025-Q1,2024-Q4
0,A. TÀI SẢN,ASSETS,assets,None,0,1,NaN,NaN,NaN,NaN
1,"I. Tiền mặt, vàng bạc, đá quý","I. Cash, gold and silver, precious stones","cash,_gold_and_silver,_precious_stones",None,1,2,6.785568e+09,6.666091e+09,5.857654e+09,5.696449e+09
2,II. Tiền gửi tại NHNN,II. Balances with the State Bank of Vietnam,balances_with_the_state_bank_of_vietnam,None,1,3,1.519747e+10,5.439937e+09,1.345751e+10,2.521975e+10
3,"III. Tiền, vàng gửi tại các TCTD khác và cho v...",III. Placements at and loans to other credit i...,placements_at_and_loans_to_other_credit_instit...,None,1,4,1.049259e+11,1.254473e+11,1.293475e+11,1.178823e+11
4,"1. Tiền, vàng gửi tại các TCTD khác",1. Placements at other credit institutions,placements_at_other_credit_institutions,None,2,5,1.049259e+11,1.254473e+11,1.293475e+11,1.177813e+11
...,...,...,...,...,...,...,...,...,...,...
72,4. Chênh lệch đánh giá lại tài sản,4. Assets revaluation differences,assets_revaluation_differences,None,2,73,NaN,NaN,NaN,NaN
73,5. Lợi nhuận chưa phân phối/Lỗ lũy kế,5. Undistributed earnings after tax/Accumulate...,undistributed_earnings_after_tax_accumulated_loss,None,2,74,2.530712e+10,2.102653e+10,2.741202e+10,2.373375e+10
74,6. Lợi ích cổ đông không kiểm soát,6. Minority's interest,minority's_interest,None,2,75,NaN,NaN,NaN,NaN
75,IX. Lợi ích của cổ đông thiểu số,IX. Minority interest,minority_interest,None,1,76,NaN,NaN,NaN,NaN
76,TỔNG NỢ PHẢI TRẢ VÀ VỐN CHỦ SỞ HỮU,TOTAL LIABILITIES AND OWNER'S EQUITY,total_liabilities_and_owner's_equity,None,0,77,9.485492e+11,9.335414e+11,8.916746e+11,8.640057e+11

#### Báo cáo kết quả kinh doanh

In [ ]:
finance.income_statement(period='year')

,item,item_en,item_id,unit,levels,row_number,2024,2023,2022,2021
0,1. Thu nhập lãi và các khoản thu nhập tương tự,1. Interest income and similar income,interest_income_and_similar_income,None,0,1,5.090275e+10,5.234680e+10,4.069883e+10,3.371381e+10
1,2. Chi phí lãi và các chi phí tương tự,2. Interest expense and similar expenses,interest_expense_and_similar_expenses,None,0,2,2.310805e+10,2.738723e+10,1.716530e+10,1.476902e+10
2,I. Thu nhập lãi thuần,I. Net interest income,net_interest_income,None,0,3,2.779470e+10,2.495957e+10,2.353353e+10,1.894479e+10
3,3. Thu nhập từ hoạt động dịch vụ,3. Fee and commission income,fee_and_commission_income,None,0,4,5.464958e+09,4.945751e+09,5.057559e+09,4.026460e+09
4,4. Chi phí hoạt động dịch vụ,4. Fee and commission expenses,fee_and_commission_expenses,None,0,5,2.226173e+09,2.023414e+09,1.531315e+09,1.132497e+09
5,II. Lãi/lỗ thuần từ hoạt động dịch vụ,II. Net fee and commission income,net_fee_and_commission_income,None,0,6,3.238785e+09,2.922337e+09,3.526244e+09,2.893963e+09
6,III. Lãi/lỗ thuần từ hoạt động kinh doanh ngoạ...,III. Net gain/(loss) from foreign currencies a...,net_gain_loss_from_foreign_currencies_and_gold...,None,0,7,1.170752e+09,1.110105e+09,1.048369e+09,8.715560e+08
7,IV. Lãi/lỗ thuần từ mua bán chứng khoán kinh d...,IV. Net gain/(loss) from trading securities,net_gain_loss_from_trading_securities,None,0,8,2.003570e+08,1.683830e+08,-3.878730e+08,4.499600e+08
8,V. Lãi/lỗ thuần từ mua bán chứng khoán đầu tư,V. Net gain/(loss) from investment securities,net_gain_loss_from_investment_securities,None,0,9,4.503120e+08,2.647140e+09,2.064800e+07,2.440510e+08
9,5. Thu nhập từ hoạt động khác,5. Other income,other_income,None,0,10,1.266132e+09,1.197217e+09,1.110494e+09,7.031590e+08
10,6. Chi phí hoạt động khác,6. Other expenses,other_expenses,None,0,11,6.424950e+08,3.338460e+08,1.208000e+08,5.636960e+08
11,VI. Lãi/lỗ thuần từ hoạt động khác,VI. Net other income,net_other_income,None,0,12,6.236370e+08,8.633710e+08,9.896940e+08,1.394630e+08
12,"VII. Thu nhập từ góp vốn, mua cổ phần",VII. Income from capital contribution and long...,income_from_capital_contribution_and_long_term...,None,0,13,3.621400e+07,7.561000e+07,5.945600e+07,2.021200e+07
13,VIII. Chi phí hoạt động,VIII. Operating expenses,operating_expenses,None,0,14,1.090260e+10,1.087429e+10,1.160504e+10,8.229776e+09
14,IX. Lợi nhuận thuần từ hoạt động kinh doanh tr...,IX. Operating profit before provision for cred...,operating_profit_before_provision_for_credit_l...,None,0,15,2.261216e+10,2.187223e+10,1.718502e+10,1.533422e+10
15,X. Chi phí dự phòng rủi ro tín dụng,X. Provision for credit losses,provision_for_credit_losses,None,0,16,1.606285e+09,1.804231e+09,7.081400e+07,3.336109e+09
16,XI. Tổng lợi nhuận trước thuế (IX-X),XI. Profit before tax,profit_before_tax,None,0,17,2.100587e+10,2.006800e+10,1.711421e+10,1.199811e+10
17,7. Chi phí thuế TNDN hiện hành,7. Current corporate income tax expenses,current_corporate_income_tax_expenses,None,0,18,4.199699e+09,3.993022e+09,3.445611e+09,2.389079e+09
18,8. Chi phí thuế TNDN hoãn lại,8. Deferred income tax expenses (*),deferred_income_tax_expenses_*,None,0,19,1.640400e+07,3.024400e+07,-1.959600e+07,6.287000e+06
19,XII. Chi phí thuế TNDN,XII. Corporate income tax,corporate_income_tax,None,0,20,4.216103e+09,4.023266e+09,3.426015e+09,2.395366e+09
20,XIII. Lợi nhuận sau thuế (XI-XII),XIII. Net profit after tax,net_profit_after_tax,None,0,21,1.678977e+10,1.604473e+10,1.368819e+10,9.602746e+09
21,XIV. Lợi ích của cổ đông thiểu số,XIV. Minority interest,minority_interest,None,0,22,NaN,NaN,NaN,NaN
22,XV. Lợi nhuận sau thuế của cổ đông của Ngân hà...,XV. Net profit atttributable to the equity hol...,net_profit_atttributable_to_the_equity_holders...,None,0,23,1.678977e+10,1.604473e+10,1.368819e+10,9.602746e+09
23,Lãi cơ bản trên cổ phiếu (BCTC) (VNÐ),Earning per share (VND),earning_per_share_vnd,None,0,24,3.669000e+03,4.092000e+03,4.008000e+03,3.498000e+03

In [ ]:
finance.income_statement(period='quarter')

,item,item_en,item_id,unit,levels,row_number,2025-Q3,2025-Q2,2025-Q1,2024-Q4
0,1. Thu nhập lãi và các khoản thu nhập tương tự,1. Interest income and similar income,interest_income_and_similar_income,None,0,1,1.504940e+10,1.429870e+10,1.332731e+10,1.351838e+10
1,2. Chi phí lãi và các chi phí tương tự,2. Interest expense and similar expenses,interest_expense_and_similar_expenses,None,0,2,8.279694e+09,7.614847e+09,6.968441e+09,6.438085e+09
2,I. Thu nhập lãi thuần,I. Net interest income,net_interest_income,None,0,3,6.769710e+09,6.683848e+09,6.358865e+09,7.080291e+09
3,3. Thu nhập từ hoạt động dịch vụ,3. Fee and commission income,fee_and_commission_income,None,0,4,1.317755e+09,1.102158e+09,1.394280e+09,1.435715e+09
4,4. Chi phí hoạt động dịch vụ,4. Fee and commission expenses,fee_and_commission_expenses,None,0,5,5.223300e+08,5.174270e+08,5.219670e+08,5.668900e+08
5,II. Lãi/lỗ thuần từ hoạt động dịch vụ,II. Net fee and commission income,net_fee_and_commission_income,None,0,6,7.954250e+08,5.847310e+08,8.723130e+08,8.688250e+08
6,III. Lãi/lỗ thuần từ hoạt động kinh doanh ngoạ...,III. Net gain/(loss) from foreign currencies a...,net_gain_loss_from_foreign_currencies_and_gold...,None,0,7,4.491500e+08,6.700050e+08,4.755900e+08,3.441670e+08
7,IV. Lãi/lỗ thuần từ mua bán chứng khoán kinh d...,IV. Net gain/(loss) from trading securities,net_gain_loss_from_trading_securities,None,0,8,3.673660e+08,3.659000e+07,2.379900e+07,-2.609000e+07
8,V. Lãi/lỗ thuần từ mua bán chứng khoán đầu tư,V. Net gain/(loss) from investment securities,net_gain_loss_from_investment_securities,None,0,9,-3.000000e+04,4.460910e+08,-1.495000e+06,2.130500e+08
9,5. Thu nhập từ hoạt động khác,5. Other income,other_income,None,0,10,3.706570e+08,1.163413e+09,2.844680e+08,4.194720e+08
10,6. Chi phí hoạt động khác,6. Other expenses,other_expenses,None,0,11,3.859200e+08,3.506900e+08,1.020830e+08,3.468820e+08
11,VI. Lãi/lỗ thuần từ hoạt động khác,VI. Net other income,net_other_income,None,0,12,-1.526300e+07,8.127230e+08,1.823850e+08,7.259000e+07
12,"VII. Thu nhập từ góp vốn, mua cổ phần",VII. Income from capital contribution and long...,income_from_capital_contribution_and_long_term...,None,0,13,1.830700e+07,5.855600e+07,3.171000e+06,5.463000e+06
13,VIII. Chi phí hoạt động,VIII. Operating expenses,operating_expenses,None,0,14,2.713933e+09,2.736160e+09,2.691892e+09,2.739350e+09
14,IX. Lợi nhuận thuần từ hoạt động kinh doanh tr...,IX. Operating profit before provision for cred...,operating_profit_before_provision_for_credit_l...,None,0,15,5.670732e+09,6.556384e+09,5.222736e+09,5.818946e+09
15,X. Chi phí dự phòng rủi ro tín dụng,X. Provision for credit losses,provision_for_credit_losses,None,0,16,2.889360e+08,4.630390e+08,6.261280e+08,1.476750e+08
16,XI. Tổng lợi nhuận trước thuế (IX-X),XI. Profit before tax,profit_before_tax,None,0,17,5.381796e+09,6.093345e+09,4.596608e+09,5.671271e+09
17,7. Chi phí thuế TNDN hiện hành,7. Current corporate income tax expenses,current_corporate_income_tax_expenses,None,0,18,1.081502e+09,1.210700e+09,9.585510e+08,1.086127e+09
18,8. Chi phí thuế TNDN hoãn lại,8. Deferred income tax expenses (*),deferred_income_tax_expenses_*,None,0,19,1.970500e+07,1.486000e+06,-4.020900e+07,3.978000e+07
19,XII. Chi phí thuế TNDN,XII. Corporate income tax,corporate_income_tax,None,0,20,1.101207e+09,1.212186e+09,9.183420e+08,1.125907e+09
20,XIII. Lợi nhuận sau thuế (XI-XII),XIII. Net profit after tax,net_profit_after_tax,None,0,21,4.280589e+09,4.881159e+09,3.678266e+09,4.545364e+09
21,XIV. Lợi ích của cổ đông thiểu số,XIV. Minority interest,minority_interest,None,0,22,NaN,NaN,NaN,NaN
22,XV. Lợi nhuận sau thuế của cổ đông của Ngân hà...,XV. Net profit atttributable to the equity hol...,net_profit_atttributable_to_the_equity_holders...,None,0,23,4.280589e+09,4.881159e+09,3.678266e+09,4.545364e+09
23,Lãi cơ bản trên cổ phiếu (BCTC) (VNÐ),Earning per share (VND),earning_per_share_vnd,None,0,24,NaN,NaN,8.230000e+02,NaN

#### Báo cáo lưu chuyển tiền tệ

In [ ]:
finance.cash_flow(period='year')

,item,item_en,item_id,unit,levels,row_number,2024,2023,2022,2021
0,Lưu chuyển tiền từ hoạt động kinh doanh,I. Cash flows from operating activities,cash_flows_from_operating_activities,None,0,58,NaN,NaN,NaN,NaN
1,1. Thu nhập lãi và các khoản thu nhập tương tự...,1. Receipts from interest and similar income,receipts_from_interest_and_similar_income,None,0,59,5.023105e+10,5.215368e+10,3.978116e+10,3.418014e+10
2,2. Chi phí lãi và các chi phí tương tự đã trả,2. Payments for interest and similar expenses,payments_for_interest_and_similar_expenses,None,0,60,-2.373758e+10,-2.526284e+10,-1.623203e+10,-1.521985e+10
3,3. Thu nhập từ hoạt động dịch vụ nhận được,3. Receipts from fee and commission income,receipts_from_fee_and_commission_income,None,0,61,2.672118e+09,2.357768e+09,3.526244e+09,2.893963e+09
4,4- Chênh lệch số tiền thực thu/thực chi từ hoạ...,4. Net cash inflow from trading activities in ...,net_cash_inflow_from_trading_activities_in_for...,None,0,62,1.822938e+09,3.882434e+09,7.971130e+08,1.184916e+09
5,5. Thu nhập khác,5. Receipts from other income,receipts_from_other_income,None,0,63,-1.640890e+08,-1.834000e+07,1.520490e+08,-9.496400e+07
6,"6. Tiền thu các khoản nợ đã được xử lý xóa, bù...",6. Receipts from collection of debts written-o...,"receipts_from_collection_of_debts_written_off,...",None,0,64,7.409380e+08,8.801790e+08,7.868040e+08,2.159740e+08
7,7. Tiền chi trả cho nhân viên và hoạt động quả...,7. Payments for staff costs and operating expe...,payments_for_staff_costs_and_operating_expenses,None,0,65,-1.074714e+10,-1.056786e+10,-1.081731e+10,-8.551243e+09
8,8. Tiền thuế thu nhập thực nộp trong kỳ,8. Corporate income tax paid for the period,corporate_income_tax_paid_for_the_period,None,0,66,-4.108348e+09,-4.003037e+09,-1.580115e+09,-2.282359e+09
9,Lưu chuyển tiền thuần từ hoạt động kinh doanh ...,Cash flow from operating activities before cha...,cash_flow_from_operating_activities_before_cha...,None,0,67,1.670989e+10,1.942198e+10,1.641391e+10,1.232657e+10
10,Những thay đổi về tài sản hoạt động,Changes in operating assets,changes_in_operating_assets,None,0,68,NaN,NaN,NaN,NaN
11,"9. (Tăng)/Giảm các khoản tiền, vàng gửi và cho...",9. (Increase)/Decrease in placements with and ...,increase_decrease_in_placements_with_and_loans...,None,0,69,-5.521656e+09,1.273080e+08,2.848001e+09,1.756384e+09
12,10. (Tăng)/Giảm các khoản về kinh doanh chứng ...,10. (Increase)/Decrease in trading securities ...,increase_decrease_in_trading_securities_and_in...,None,0,70,-4.356137e+10,-3.695212e+09,-6.448600e+09,-4.789660e+08
13,11. (Tăng)/Giảm các công cụ tài chính phái sin...,11. (Increase)/Decrease in derivatives and oth...,increase_decrease_in_derivatives_and_other_fin...,None,0,71,-5.599200e+07,1.000720e+08,1.264730e+08,-1.720720e+08
14,12. (Tăng)/Giảm các khoản cho vay khách hàng,12. (Increase)/Decrease in loans and advances ...,increase_decrease_in_loans_and_advances_to_cus...,None,0,72,-9.308440e+10,-7.389687e+10,-5.179371e+10,-5.043355e+10
15,13. Giảm nguồn dự phòng để bù đắp tổn thất các...,13. (Decrease)/Increase in provisions for damages,decrease_increase_in_provisions_for_damages,None,0,73,-2.328800e+08,-1.287015e+09,-1.032666e+09,-4.248850e+08
16,14. (Tăng)/Giảm khác về tài sản hoạt động,14. (Increase)/Decrease in other operating ass...,increase_decrease_in_other_operating_assets,None,0,74,2.710100e+08,-5.024300e+07,-1.946491e+09,6.204040e+08
17,Những thay đổi về công nợ hoạt động,Changes in operating liabilities,changes_in_operating_liabilities,None,0,75,NaN,NaN,NaN,NaN
18,15. Tăng/(Giảm) các khoản nợ chính phủ và NHNN,15. Increase/(Decrease) in due to the Governme...,increase_decrease_in_due_to_the_government_and...,None,0,76,7.954765e+09,-5.057880e+08,5.058760e+08,NaN
19,"16. Tăng/(Giảm) các khoản tiền gửi, tiền vay c...",16. Increase/(Decrease) in placements and borr...,increase_decrease_in_placements_and_borrowings...,None,0,77,2.208501e+10,2.166582e+10,1.344690e+10,3.051870e+10
20,17. Tăng/(Giảm) tiền gửi của khách hàng (bao g...,17. Increase/(Decrease) in deposit from custom...,increase_decrease_in_deposit_from_customers_in...,None,0,78,5.460185e+10,6.874994e+10,3.403212e+10,2.672483e+10
21,18. Tăng/(Giảm) phát hành giấy tờ có giá (ngoạ...,18. Increase/(Decrease) in valuable papers iss...,increase_decrease_in_valuable_papers_issued_ex...,None,0,79,4.923314e+10,8.099170e+09,1.374990e+10,1.135695e+10
22,"19. Tăng/(Giảm) vốn tài trợ, ủy thác đầu tư, c...",19. Increase/(Decrease) in funds received from...,increase_decrease_in_funds_received_from_gover...,None,0,80,-1.352600e+07,-1.865400e+07,-2.587800e+07,-3.063900e+07
23,20. Tăng/(Giảm) các công cụ tài chính phái sin...,20. Increase/(Decrease) in derivatives and oth...,increase_decrease_in_derivatives_and_other_fin...,None,0,81,-1.171260e+08,1.171260e+08,1.600161e+09,NaN
24,21. Tăng/(Giảm) khác về công nợ hoạt động,21. Increase/(Decrease) in other operating lia...,increase_decrease_in_other_operating_liabilities,None,0,82,1.027680e+08,-1.689943e+09,-2.014630e+08,8.163652e+09
25,22. Chi từ các quỹ của TCTD,22. Payments from reserves,payments_from_reserves,None,0,83,-1.249000e+06,-1.500000e+06,NaN,-1.483000e+06
26,I - Lưu chuyển tiền thuần từ hoạt động kinh do...,Net cash flows from operating activities,net_cash_flows_from_operating_activities,None,0,84,8.370231e+09,3.713620e+10,2.127454e+10,3.992590e+10
27,Lưu chuyển tiền từ hoạt động đầu tư,II. Cash flows from investing activities,cash_flows_from_investing_activities,None,0,85,NaN,NaN,NaN,NaN
28,1. Mua sắm tài sản cố định,1. Purchase of fixed assets,purchase_of_fixed_assets,None,0,86,-9.197400e+08,-1.276249e+09,-5.115130e+08,-6.361000e+08
29,"2. Tiền thu từ thanh lý, nhượng bán TSCĐ",2. Receipts from disposal of fixed assets,receipts_from_disposal_of_fixed_assets,None,0,87,1.478650e+08,4.038000e+06,4.741000e+06,3.265000e+06
30,"3. Tiền chi từ thanh lý, nhượng bán TSCĐ",3. Payments for disposal of fixed assets,payments_for_disposal_of_fixed_assets,None,0,88,NaN,NaN,NaN,NaN
31,4. Mua sắm bất động sản đầu tư,4. Purchase of investment properties,purchase_of_investment_properties,None,0,89,NaN,NaN,NaN,NaN
32,"5. Tiền thu từ bán, thanh lý bất động sản đầu tư",5. Receipts from disposal of investment proper...,receipts_from_disposal_of_investment_properties,None,0,90,NaN,NaN,8.536400e+07,1.484530e+08
33,"6. Tiền chi ra do bán, thanh lý bất động sản đ...",6. Payments for disposal of investment properties,payments_for_disposal_of_investment_properties,None,0,91,NaN,NaN,NaN,NaN
34,"7. Tiền chi đầu tư, góp vốn vào các đơn vị khá...",7. Payments for investment in other entities,payments_for_investment_in_other_entities,None,0,92,NaN,NaN,-1.052000e+07,NaN
35,"8. Tiền thu đầu tư, góp vốn vào các đơn vị khá...",8. Collections on investment in other entities,collections_on_investment_in_other_entities,None,0,93,3.507000e+06,NaN,6.451000e+06,NaN
36,9. Tiền thu cổ tức và lợi nhuận được chia từ c...,9. Dividends and profit received,dividends_and_profit_received,None,0,94,3.505800e+07,7.495500e+07,5.959900e+07,2.197900e+07
37,II- Lưu chuyển tiền thuần từ hoạt động đầu tư,Net cash flows from investing activities,net_cash_flows_from_investing_activities,None,0,95,-7.333100e+08,-1.197256e+09,-3.658780e+08,-4.624030e+08
38,Lưu chuyển tiền từ hoạt động tài chính,III. Cash flows from financing activities,cash_flows_from_financing_activities,None,0,96,NaN,NaN,NaN,NaN
39,1. Tăng vốn cổ phần từ góp vốn và/hoặc phát hà...,1. Receipts from equity issue and owner's capi...,receipts_from_equity_issue_and_owner's_capital...,None,0,97,NaN,NaN,NaN,NaN
40,2. Tiền thu từ phát hành giấy tờ có giá dài hạ...,2. Receipts from issue of valuable papers qual...,receipts_from_issue_of_valuable_papers_qualifi...,None,0,98,NaN,NaN,NaN,NaN
41,3. Tiền chi thanh toán giấy tờ có giá dài hạn ...,3. Payments for issue of valuable papers quali...,payments_for_issue_of_valuable_papers_qualifie...,None,0,99,NaN,NaN,NaN,-2.884000e+09
42,"4. Cổ tức trả cho cổ đông, lợi nhuận đã chia","4. Dividends paid, profits distributed to owners","dividends_paid,_profits_distributed_to_owners",None,0,100,-3.884051e+09,-3.377435e+09,NaN,NaN
43,5. Tiền chi ra mua cổ phiếu quỹ,5. Payments for purchase of treasury shares,payments_for_purchase_of_treasury_shares,None,0,101,NaN,NaN,NaN,NaN
44,6. Tiền thu được do bán cổ phiếu quỹ,6. Receipts from disposal of treasury shares,receipts_from_disposal_of_treasury_shares,None,0,102,NaN,NaN,NaN,NaN
45,III- Lưu chuyển tiền thuần từ hoạt động tài chính,Net cash flows from financing activities,net_cash_flows_from_financing_activities,None,0,103,-3.884051e+09,-3.377435e+09,NaN,-2.884000e+09
46,IV- Lưu chuyển tiền thuần trong kỳ,Net cash flows during the period,net_cash_flows_during_the_period,None,0,104,3.752870e+09,3.256151e+10,2.090866e+10,3.657950e+10
47,V- Tiền và các khoản tương đương tiền tại thời...,Cash and cash equivalents at beginning of the ...,cash_and_cash_equivalents_at_beginning_of_the_...,None,0,105,1.360717e+11,1.035102e+11,8.260157e+10,4.602207e+10
48,VI- Điều chỉnh ảnh hưởng của thay đổi tỷ giá,Exchange difference due to re-valuation of end...,exchange_difference_due_to_re_valuation_of_end...,None,0,106,NaN,NaN,NaN,NaN
49,VII. Tiền và các khoản tương đương tiền tại th...,Cash and cash equivalents at end of the period,cash_and_cash_equivalents_at_end_of_the_period,None,0,107,1.398246e+11,1.360717e+11,1.035102e+11,8.260157e+10

In [ ]:
finance.income_statement(period='quarter')

,item,item_en,item_id,unit,levels,row_number,2025-Q3,2025-Q2,2025-Q1,2024-Q4
0,1. Thu nhập lãi và các khoản thu nhập tương tự,1. Interest income and similar income,interest_income_and_similar_income,None,0,1,1.504940e+10,1.429870e+10,1.332731e+10,1.351838e+10
1,2. Chi phí lãi và các chi phí tương tự,2. Interest expense and similar expenses,interest_expense_and_similar_expenses,None,0,2,8.279694e+09,7.614847e+09,6.968441e+09,6.438085e+09
2,I. Thu nhập lãi thuần,I. Net interest income,net_interest_income,None,0,3,6.769710e+09,6.683848e+09,6.358865e+09,7.080291e+09
3,3. Thu nhập từ hoạt động dịch vụ,3. Fee and commission income,fee_and_commission_income,None,0,4,1.317755e+09,1.102158e+09,1.394280e+09,1.435715e+09
4,4. Chi phí hoạt động dịch vụ,4. Fee and commission expenses,fee_and_commission_expenses,None,0,5,5.223300e+08,5.174270e+08,5.219670e+08,5.668900e+08
5,II. Lãi/lỗ thuần từ hoạt động dịch vụ,II. Net fee and commission income,net_fee_and_commission_income,None,0,6,7.954250e+08,5.847310e+08,8.723130e+08,8.688250e+08
6,III. Lãi/lỗ thuần từ hoạt động kinh doanh ngoạ...,III. Net gain/(loss) from foreign currencies a...,net_gain_loss_from_foreign_currencies_and_gold...,None,0,7,4.491500e+08,6.700050e+08,4.755900e+08,3.441670e+08
7,IV. Lãi/lỗ thuần từ mua bán chứng khoán kinh d...,IV. Net gain/(loss) from trading securities,net_gain_loss_from_trading_securities,None,0,8,3.673660e+08,3.659000e+07,2.379900e+07,-2.609000e+07
8,V. Lãi/lỗ thuần từ mua bán chứng khoán đầu tư,V. Net gain/(loss) from investment securities,net_gain_loss_from_investment_securities,None,0,9,-3.000000e+04,4.460910e+08,-1.495000e+06,2.130500e+08
9,5. Thu nhập từ hoạt động khác,5. Other income,other_income,None,0,10,3.706570e+08,1.163413e+09,2.844680e+08,4.194720e+08
10,6. Chi phí hoạt động khác,6. Other expenses,other_expenses,None,0,11,3.859200e+08,3.506900e+08,1.020830e+08,3.468820e+08
11,VI. Lãi/lỗ thuần từ hoạt động khác,VI. Net other income,net_other_income,None,0,12,-1.526300e+07,8.127230e+08,1.823850e+08,7.259000e+07
12,"VII. Thu nhập từ góp vốn, mua cổ phần",VII. Income from capital contribution and long...,income_from_capital_contribution_and_long_term...,None,0,13,1.830700e+07,5.855600e+07,3.171000e+06,5.463000e+06
13,VIII. Chi phí hoạt động,VIII. Operating expenses,operating_expenses,None,0,14,2.713933e+09,2.736160e+09,2.691892e+09,2.739350e+09
14,IX. Lợi nhuận thuần từ hoạt động kinh doanh tr...,IX. Operating profit before provision for cred...,operating_profit_before_provision_for_credit_l...,None,0,15,5.670732e+09,6.556384e+09,5.222736e+09,5.818946e+09
15,X. Chi phí dự phòng rủi ro tín dụng,X. Provision for credit losses,provision_for_credit_losses,None,0,16,2.889360e+08,4.630390e+08,6.261280e+08,1.476750e+08
16,XI. Tổng lợi nhuận trước thuế (IX-X),XI. Profit before tax,profit_before_tax,None,0,17,5.381796e+09,6.093345e+09,4.596608e+09,5.671271e+09
17,7. Chi phí thuế TNDN hiện hành,7. Current corporate income tax expenses,current_corporate_income_tax_expenses,None,0,18,1.081502e+09,1.210700e+09,9.585510e+08,1.086127e+09
18,8. Chi phí thuế TNDN hoãn lại,8. Deferred income tax expenses (*),deferred_income_tax_expenses_*,None,0,19,1.970500e+07,1.486000e+06,-4.020900e+07,3.978000e+07
19,XII. Chi phí thuế TNDN,XII. Corporate income tax,corporate_income_tax,None,0,20,1.101207e+09,1.212186e+09,9.183420e+08,1.125907e+09
20,XIII. Lợi nhuận sau thuế (XI-XII),XIII. Net profit after tax,net_profit_after_tax,None,0,21,4.280589e+09,4.881159e+09,3.678266e+09,4.545364e+09
21,XIV. Lợi ích của cổ đông thiểu số,XIV. Minority interest,minority_interest,None,0,22,NaN,NaN,NaN,NaN
22,XV. Lợi nhuận sau thuế của cổ đông của Ngân hà...,XV. Net profit atttributable to the equity hol...,net_profit_atttributable_to_the_equity_holders...,None,0,23,4.280589e+09,4.881159e+09,3.678266e+09,4.545364e+09
23,Lãi cơ bản trên cổ phiếu (BCTC) (VNÐ),Earning per share (VND),earning_per_share_vnd,None,0,24,NaN,NaN,8.230000e+02,NaN

#### Chỉ số tài chính

In [ ]:
finance.ratio(period='year')

,item,item_en,item_id,unit,levels,row_number,2024,2023,2022,2021
0,Thu nhập trên mỗi cổ phần của 4 quý gần nhất (...,Trailing EPS,trailing_eps,VNĐ,0,1,3974.57,4368.94,4441.71,3900.36
1,Giá trị sổ sách của cổ phiếu (BVPS),Book value per share (BVPS),book_value_per_share_bvps,VNĐ,0,2,18685.49,18268.55,17302.68,16617.98
2,Chỉ số giá thị trường trên thu nhập (P/E),P/E,p_e,Lần,0,3,6.49,5.47,4.93,8.85
3,Chỉ số giá thị trường trên giá trị sổ sách (P/B),P/B,p_b,Lần,0,4,1.38,1.31,1.27,2.08
4,Tỷ suất cổ tức,Dividend yield,dividend_yield,%,0,5,0.04,0.04,0.00,0.00
5,Beta,Beta,beta,Lần,0,6,0.88,1.01,1.07,0.56
6,Tỷ suất lợi nhuận trên vốn chủ sở hữu bình quâ...,ROE,roe,%,0,7,21.75,24.80,26.49,23.90
7,Tỷ suất sinh lợi trên tổng tài sản bình quân (...,ROA,roa,%,0,8,2.12,2.42,2.41,1.98
8,Tỷ suất sinh lợi của Tài sản Có sinh lãi (YOEA),Yield on earning assets (YOEA),yield_on_earning_assets_yoea,%,0,9,6.61,8.16,7.45,7.27
9,Tỷ lệ chi phí hình thành Tài sản Có sinh lãi (...,Cost of funding earning assets (COF),cost_of_funding_earning_assets_cof,%,0,10,3.34,4.76,3.46,3.42
10,Tỷ lệ thu nhập lãi thuần (NIM),Net interest margin (NIM),net_interest_margin_nim,%,0,11,3.61,3.89,4.31,4.09
11,Tỷ lệ chi phí hoạt động/Tổng thu nhập HĐKD trư...,Cost Income Ratio (CIR),cost_income_ratio_cir,%,0,12,32.53,33.21,40.31,34.93
12,ROE bình quân 4 quý gần nhất,ROE Trailling,roe_trailling,%,0,13,0.00,0.00,0.00,0.00
13,ROA bình quân 4 quý gần nhất,ROA Trailling,roa_trailling,%,0,14,0.00,0.00,0.00,0.00
14,Tăng trưởng lợi nhuận trước thuế,Profit before tax,profit_before_tax,%,0,15,4.67,17.26,42.64,25.03
15,Tăng trưởng lợi nhuận sau thuế của CĐ ngân hà...,Profit after tax for shareholders of the paren...,profit_after_tax_for_shareholders_of_the_paren...,%,0,16,4.64,17.22,42.54,24.99
16,Tăng trưởng tổng tài sản,Total assets,total_assets,%,0,17,20.20,18.25,15.18,18.73
17,Tăng trưởng vốn chủ sở hữu,Owner's equity,owner's_equity,%,0,18,17.62,21.42,30.15,26.67
18,Tăng trưởng vốn điều lệ,Charter capital,charter_capital,%,0,19,15.00,15.00,25.00,25.00
19,Tăng trưởng dư nợ cho vay,Deposits from customers,deposits_from_customers,%,0,20,19.09,17.86,14.31,16.19
20,Tăng trưởng huy động vốn khách hàng,Deposits from customers,deposits_from_customers,%,0,21,11.31,16.61,8.96,7.57
21,Tăng trưởng thu nhập lãi thuần,Net interest income,net_interest_income,%,0,22,11.36,6.06,24.22,29.92
22,Tăng trưởng dự phòng rủi ro tín dụng,Provisions for loan losses,provisions_for_loan_losses,%,0,23,25.34,10.56,-16.41,98.67
23,Tăng trưởng thu phí dịch vụ thuần,Net fee and commission income,net_fee_and_commission_income,%,0,24,10.83,-17.13,21.85,70.77
24,Tăng trưởng tổng thu nhập HĐKD trước dự phòng,Operating profit before provision for credit l...,operating_profit_before_provision_for_credit_l...,%,0,25,3.38,27.27,12.07,45.53
25,Tăng trưởng tổng chi phí HĐKD,Operating expenses,operating_expenses,%,0,26,0.26,-6.30,41.01,7.94
26,Dư nợ cho vay khách hàng/Tổng vốn huy động (LDR),Outstanding loans/Customer deposits,outstanding_loans_customer_deposits,%,0,27,76.56,78.06,78.56,77.85
27,Dư nợ cho vay/Tổng tài sản Có,Outstanding loans/Total assets,outstanding_loans_total_assets,%,0,28,67.21,67.84,68.06,68.57
28,Vốn chủ sở hữu/Tổng vốn huy động,Equity/Deposits from customers,equity_deposits_from_customers,%,0,29,11.00,11.36,11.10,0.00
29,Vốn chủ sở hữu/Tổng tài sản Có,Equity/Total assets,equity_total_assets,%,0,30,9.66,9.87,9.61,8.51
30,Dự phòng rủi ro tín dụng/Tổng dư nợ,Loan loss provision ratio,loan_loss_provision_ratio,%,0,31,-0.01,-0.01,-0.01,-0.02
31,Tài sản Có sinh lãi/Tổng tài sản Có,Earning assets/Total assets,earning_assets_total_assets,%,0,32,97.79,96.62,96.88,95.41

In [ ]:
finance.ratio(period='quarter')

,item,item_en,item_id,unit,levels,row_number,2025-Q3,2025-Q2,2025-Q1,2024-Q4
0,Thu nhập trên mỗi cổ phần của 4 quý gần nhất (...,Trailing EPS,trailing_eps,VNĐ,0,1,3730.45,3782.19,3797.57,3974.57
1,Giá trị sổ sách của cổ phiếu (BVPS),Book value per share (BVPS),book_value_per_share_bvps,VNĐ,0,2,17796.69,16978.09,19494.35,18685.49
2,Chỉ số giá thị trường trên thu nhập (P/E),P/E,p_e,Lần,0,3,6.84,5.63,6.85,6.49
3,Chỉ số giá thị trường trên giá trị sổ sách (P/B),P/B,p_b,Lần,0,4,1.43,1.25,1.33,1.38
4,Tỷ suất cổ tức,Dividend yield,dividend_yield,%,0,5,0.04,0.05,0.04,0.04
5,Beta,Beta,beta,Lần,0,6,0.91,0.85,0.82,0.88
6,Tỷ suất lợi nhuận trên vốn chủ sở hữu bình quâ...,ROE,roe,%,0,7,4.79,5.60,4.31,5.60
7,Tỷ suất sinh lợi trên tổng tài sản bình quân (...,ROA,roa,%,0,8,0.45,0.53,0.42,0.55
8,Tỷ suất sinh lợi của Tài sản Có sinh lãi (YOEA),Yield on earning assets (YOEA),yield_on_earning_assets_yoea,%,0,9,1.63,1.57,1.53,1.60
9,Tỷ lệ chi phí hình thành Tài sản Có sinh lãi (...,Cost of funding earning assets (COF),cost_of_funding_earning_assets_cof,%,0,10,1.00,0.95,0.90,0.90
10,Tỷ lệ thu nhập lãi thuần (NIM),Net interest margin (NIM),net_interest_margin_nim,%,0,11,0.73,0.73,0.73,0.84
11,Tỷ lệ chi phí hoạt động/Tổng thu nhập HĐKD trư...,Cost Income Ratio (CIR),cost_income_ratio_cir,%,0,12,32.37,29.44,34.01,32.01
12,ROE bình quân 4 quý gần nhất,ROE Trailling,roe_trailling,%,0,13,19.92,20.17,20.44,21.53
13,ROA bình quân 4 quý gần nhất,ROA Trailling,roa_trailling,%,0,14,1.91,1.96,2.01,2.14
14,Tăng trưởng lợi nhuận trước thuế,Profit before tax,profit_before_tax,%,0,15,11.10,8.84,-6.04,12.45
15,Tăng trưởng lợi nhuận sau thuế của CĐ ngân hà...,Profit after tax for shareholders of the paren...,profit_after_tax_for_shareholders_of_the_paren...,%,0,16,10.60,9.23,-5.82,13.46
16,Tăng trưởng tổng tài sản,Total assets,total_assets,%,0,17,22.02,21.29,22.60,20.20
17,Tăng trưởng vốn chủ sở hữu,Owner's equity,owner's_equity,%,0,18,15.93,16.60,16.42,17.62
18,Tăng trưởng vốn điều lệ,Charter capital,charter_capital,%,0,19,15.00,15.00,15.00,15.00
19,Tăng trưởng dư nợ cho vay,Deposits from customers,deposits_from_customers,%,0,20,20.59,15.19,18.31,19.09
20,Tăng trưởng huy động vốn khách hàng,Deposits from customers,deposits_from_customers,%,0,21,11.50,10.89,11.68,11.31
21,Tăng trưởng thu nhập lãi thuần,Net interest income,net_interest_income,%,0,22,-1.62,-6.01,-5.40,12.57
22,Tăng trưởng dự phòng rủi ro tín dụng,Provisions for loan losses,provisions_for_loan_losses,%,0,23,1.26,-4.64,-6.10,1.17
23,Tăng trưởng thu phí dịch vụ thuần,Net fee and commission income,net_fee_and_commission_income,%,0,24,6.46,-33.37,17.06,19.46
24,Tăng trưởng tổng thu nhập HĐKD trước dự phòng,Operating profit before provision for credit l...,operating_profit_before_provision_for_credit_l...,%,0,25,9.00,5.98,-3.36,8.46
25,Tăng trưởng tổng chi phí HĐKD,Operating expenses,operating_expenses,%,0,26,-7.49,10.97,-2.61,-9.09
26,Dư nợ cho vay khách hàng/Tổng vốn huy động (LDR),Outstanding loans/Customer deposits,outstanding_loans_customer_deposits,%,0,27,80.21,76.89,76.34,76.56
27,Dư nợ cho vay/Tổng tài sản Có,Outstanding loans/Total assets,outstanding_loans_total_assets,%,0,28,70.55,67.89,67.16,67.21
28,Vốn chủ sở hữu/Tổng vốn huy động,Equity/Deposits from customers,equity_deposits_from_customers,%,0,29,0.11,0.11,0.11,0.11
29,Vốn chủ sở hữu/Tổng tài sản Có,Equity/Total assets,equity_total_assets,%,0,30,9.64,9.34,9.77,9.66
30,Dự phòng rủi ro tín dụng/Tổng dư nợ,Loan loss provision ratio,loan_loss_provision_ratio,%,0,31,-0.01,-0.01,-0.01,-0.01
31,Tài sản Có sinh lãi/Tổng tài sản Có,Earning assets/Total assets,earning_assets_total_assets,%,0,32,97.31,97.52,97.75,97.79

### VCI

In [ ]:
from vnstock import Finance
finance = Finance(symbol='ACB', source='VCI')

#### Bảng cân đối kế toán

In [ ]:
finance.balance_sheet(period='year', lang='vi', dropna=True)

,CP,Năm,TỔNG CỘNG TÀI SẢN (đồng),Tiền và tương đương tiền (đồng),Tiền gửi tại ngân hàng nhà nước Việt Nam,Tiền gửi tại các TCTD khác và cho vay các TCTD khác,Chứng khoán kinh doanh,_Chứng khoán kinh doanh,Dự phòng giảm giá chứng khoán kinh doanh,Các công cụ tài chính phái sinh và khoản nợ tài chính khác,...,Tiền gửi của khách hàng,_Các công cụ tài chính phái sinh và khoản nợ tài chính khác,"Vốn tài trợ, uỷ thác đầu tư của CP và các tổ chức TD khác",Phát hành giấy tờ có giá,Các khoản nợ khác,VỐN CHỦ SỞ HỮU (đồng),Vốn của tổ chức tín dụng,Quỹ của tổ chức tín dụng,Lãi chưa phân phối (đồng),Vốn góp của chủ sở hữu (đồng)
0,ACB,2024,864005703000000,5696449000000,25219753000000,117882259000000,3881151000000,4029088000000,-147937000000,55992000000,...,537304578000000,0,28008000000,101650446000000,22014472000000,83461678000000,44938358000000,14789568000000,23733752000000,44666579000000
1,ACB,2023,718794589000000,6909300000000,18504814000000,114873931000000,7177069000000,7323489000000,-146420000000,0,...,482702731000000,117126000000,41534000000,52410014000000,23060473000000,70955961000000,39112283000000,11557435000000,20286243000000,38840504000000
2,ACB,2022,607875185000000,8460892000000,13657531000000,85971313000000,1131327000000,1320941000000,-189614000000,100072000000,...,413952789000000,0,60188000000,44304367000000,22772462000000,58438663000000,34046130000000,9220125000000,15172408000000,33774351000000
3,ACB,2021,527769944000000,7509877000000,32349574000000,49818776000000,11259731000000,11325371000000,-65640000000,226545000000,...,379920669000000,0,86066000000,30547883000000,17920478000000,44900909000000,27291260000000,7164297000000,10445352000000,27019481000000
4,ACB,2020,444530104000000,6967918000000,16616798000000,31671245000000,6167917000000,6285763000000,-117846000000,54473000000,...,353195838000000,0,116705000000,22049697000000,9844459000000,35448163000000,21887364000000,5741759000000,7819040000000,21615585000000
5,ACB,2019,383514439000000,6437812000000,10420306000000,30341599000000,2985262000000,3145903000000,-160641000000,87753000000,...,308129391000000,0,156147000000,20830836000000,7384134000000,27765359000000,16799171000000,4595902000000,6370286000000,16627373000000
6,ACB,2018,329333241000000,6129169000000,10683536000000,18769776000000,1177972000000,1339157000000,-161185000000,0,...,269998503000000,38198000000,160093000000,8290918000000,6035148000000,21017899000000,12220152000000,3693069000000,5104678000000,12885877000000
7,ACB,2017,284316123000000,4851710000000,8314574000000,8941727000000,1236555000000,1239991000000,-3436000000,0,...,241392932000000,10491000000,136466000000,6761000000000,4530641000000,16030847000000,9607514000000,2913780000000,3509553000000,10273239000000
8,ACB,2016,233680877000000,3541388000000,5119306000000,8152027000000,1183306000000,1211314000000,-28008000000,16065000000,...,207051269000000,0,122697000000,6615000000000,3594080000000,14062716000000,8711240000000,2590181000000,2761295000000,9376965000000
9,ACB,2015,201456985000000,2806088000000,4608680000000,10122200000000,100457000000,103034000000,-2577000000,47603000000,...,174918997000000,0,161678000000,3075000000000,2901457000000,12787542000000,8711240000000,2374178000000,1702124000000,9376965000000
10,ACB,2014,179609771000000,2496287000000,3357730000000,4559007000000,1105122000000,1108232000000,-3110000000,14403000000,...,154613588000000,0,188155000000,3078000000000,3187487000000,12397303000000,8711841000000,2207666000000,1477796000000,9376965000000
11,ACB,2013,166598989000000,2043490000000,3065322000000,7215519000000,851161000000,1078309000000,-227148000000,150000000,...,138110836000000,0,363345000000,3500000000000,2743684000000,12504202000000,9117544000000,2034952000000,1351706000000,9376965000000
12,ACB,2011,281019319000000,8709990000000,5075817000000,81274021000000,850459000000,1048787000000,-198328000000,1016447000000,...,142218091000000,0,332318000000,50708499000000,34556973000000,11959092000000,9376965000000,1753237000000,828890000000,9376965000000
13,ACB,2010,205102950000000,10884762000000,2914353000000,33961250000000,978355000000,1167950000000,-189595000000,78172000000,...,106936611000000,0,379768000000,38234151000000,10594023000000,11376757000000,9376965000000,1209552000000,790240000000,9376965000000

In [ ]:
finance.balance_sheet(period='quarter', lang='en', dropna=True).head()

,ticker,yearReport,lengthReport,TOTAL ASSETS (Bn. VND),Cash and cash equivalents (Bn. VND),Balances with the SBV,Placements with and loans to other credit institutions,"Trading Securities, net",Trading Securities,Provision for diminution in value of Trading Securities,...,"Funds received from Gov, international and other institutions",Convertible bonds/CDs and other valuable papers issued,Other liabilities,OWNER'S EQUITY(Bn.VND),Capital,Reserves,Foreign Currency Difference reserve,Undistributed earnings (Bn. VND),Paid-in capital (Bn. VND),MINORITY INTERESTS
0,ACB,2025,3,948549176000000,6785568000000,15197467000000,104925948000000,5918486000000,6072639000000,-154153000000,...,22456000000,113387071000000,22703870000000,91415500000000,51638345000000,14789568000000,-319534000000,25307121000000,51366566000000,0
1,ACB,2025,2,933541420000000,6666091000000,5439937000000,125447269000000,4958406000000,5160049000000,-201643000000,...,24547000000,139552843000000,21741640000000,87210629000000,51638345000000,14789568000000,-243816000000,21026532000000,51366566000000,0
2,ACB,2025,1,891674563000000,5857654000000,13457514000000,129347480000000,4307534000000,4479661000000,-172127000000,...,26725000000,114051801000000,20047729000000,87074577000000,44938358000000,14789568000000,-65367000000,27412018000000,44666579000000,0
3,ACB,2024,4,864005703000000,5696449000000,25219753000000,117882259000000,3881151000000,4029088000000,-147937000000,...,28008000000,101650446000000,22014472000000,83461678000000,44938358000000,14789568000000,0,23733752000000,44666579000000,0
4,ACB,2024,3,777392922000000,5870526000000,8392393000000,92090423000000,6965867000000,7059448000000,-93581000000,...,31641000000,90366104000000,22478444000000,78854261000000,44938358000000,11557435000000,-62053000000,22420521000000,44666579000000,0

#### Báo cáo kết quả kinh doanh

In [ ]:
finance.income_statement(period='year', lang='vi', dropna=True).head()

,CP,Năm,Doanh thu (đồng),Tăng trưởng doanh thu (%),Lợi nhuận sau thuế của Cổ đông công ty mẹ (đồng),Tăng trưởng lợi nhuận (%),Thu nhập lãi và các khoản tương tự,Chi phí lãi và các khoản tương tự,Thu nhập lãi thuần,Thu nhập từ hoạt động dịch vụ,...,Chi phí quản lý DN,LN từ HĐKD trước CF dự phòng,Chi phí dự phòng rủi ro tín dụng,LN trước thuế,Thuế TNDN,Chi phí thuế TNDN hiện hành,Chi phí thuế TNDN hoãn lại,Lợi nhuận thuần,Cổ đông của Công ty mẹ,Lãi cơ bản trên cổ phiếu
0,ACB,2024,50902749000000,-0.027586,16789768000000,0.046435,50902749000000,-23108047000000,27794702000000,5464958000000,...,-10902603000000,22612156000000,-1606285000000,21005871000000,-4216103000000,-4199699000000,-16404000000,16789768000000,16789768000000,3669
1,ACB,2023,52346796000000,0.286199,16044733000000,0.172159,52346796000000,-27387226000000,24959570000000,4945751000000,...,-10874286000000,21872230000000,-1804231000000,20067999000000,-4023266000000,-3993022000000,-30244000000,16044733000000,16044733000000,3559
2,ACB,2022,40698834000000,0.207186,13688193000000,0.425446,40698834000000,-17165305000000,23533529000000,5057559000000,...,-11605045000000,17185022000000,-70814000000,17114208000000,-3426015000000,-3445611000000,19596000000,13688193000000,13688193000000,3486
3,ACB,2021,33713810000000,0.058327,9602746000000,0.249898,33713810000000,-14769018000000,18944792000000,4026460000000,...,-8229776000000,15334221000000,-3336109000000,11998112000000,-2395366000000,-2389079000000,-6287000000,9602746000000,9602746000000,2799
4,ACB,2020,31855748000000,0.124948,7682823000000,0.278353,31855748000000,-17273625000000,14582123000000,2803484000000,...,-7624268000000,10537041000000,-941153000000,9595888000000,-1913065000000,-1940681000000,27616000000,7682823000000,7682823000000,2808

In [ ]:
finance.income_statement(period='quarter', lang='en', dropna=True).head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Interest and Similar Income,Interest and Similar Expenses,Net Interest Income,...,General & Admin Expenses,Operating Profit before Provision,Provision for credit losses,Profit before tax,Tax For the Year,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Attributable to parent company,EPS_basis
0,ACB,2025,3,15049404000000,0.164628,4280589000000,0.105982,15049404000000,-8279694000000,6769710000000,...,-2713933000000,5670732000000,-288936000000,5381796000000,-1101207000000,-1081502000000,-19705000000,4280589000000,4280589000000,0
1,ACB,2025,2,14298695000000,0.146214,4881159000000,0.092326,14298695000000,-7614847000000,6683848000000,...,-2736160000000,6556384000000,-463039000000,6093345000000,-1212186000000,-1210700000000,-1486000000,4881159000000,4881159000000,0
2,ACB,2025,1,13327306000000,0.111758,3678266000000,-0.058164,13327306000000,-6968441000000,6358865000000,...,-2691892000000,5222736000000,-626128000000,4596608000000,-918342000000,-958551000000,40209000000,3678266000000,3678266000000,0
3,ACB,2024,4,13518376000000,0.080173,4545364000000,0.134560,13518376000000,-6438085000000,7080291000000,...,-2739350000000,5818946000000,-147675000000,5671271000000,-1125907000000,-1086127000000,-39780000000,4545364000000,4545364000000,1017
4,ACB,2024,3,12922067000000,-0.007819,3870395000000,-0.041407,12922067000000,-6040680000000,6881387000000,...,-2933714000000,5202287000000,-358243000000,4844044000000,-973649000000,-971306000000,-2343000000,3870395000000,3870395000000,0

#### Báo cáo lưu chuyển tiền tệ

In [ ]:
finance.cash_flow(period='year', dropna=True).head()

,ticker,yearReport,Profits from other activities,Operating profit before changes in working capital,Net Cash Flows from Operating Activities before BIT,Payment from reserves,Purchase of fixed assets,Gain on Dividend,Net Cash Flows from Investing Activities,Increase in charter captial,Cash flows from financial activities,Net increase/decrease in cash and cash equivalents,Cash and cash equivalents,Foreign exchange differences Adjustment,Cash and Cash Equivalents at the end of period,Net cash inflows/outflows from operating activities,Proceeds from disposal of fixed assets,Investment in other entities,Proceeds from divestment in other entities,Dividends paid
0,ACB,2024,-164089000000,16709886000000,8371480000000,-1249000000,-919740000000,35058000000,-733310000000,0,-3884051000000,3752870000000,136071738000000,0,139824608000000,8370231000000,147865000000,0,3507000000,-3884051000000
1,ACB,2023,-18340000000,19421985000000,37137701000000,-1500000000,-1276249000000,74955000000,-1197256000000,0,-3377435000000,32561510000000,103510228000000,0,136071738000000,37136201000000,4038000000,0,0,-3377435000000
2,ACB,2022,152049000000,16413910000000,21476002000000,-201463000000,-511513000000,59599000000,-365878000000,0,0,20908661000000,82601567000000,0,103510228000000,21274539000000,4741000000,-10520000000,6451000000,0
3,ACB,2021,-94964000000,12326573000000,39927382000000,-1483000000,-636100000000,21979000000,-462403000000,0,-2884000000000,36579496000000,46022071000000,0,82601567000000,39925899000000,3265000000,0,0,0
4,ACB,2020,67987000000,9688384000000,10880417000000,-1156000000,-423132000000,17573000000,-395503000000,0,-140600000000,10343158000000,35678913000000,0,46022071000000,10879261000000,3336000000,0,0,0

In [ ]:
finance.income_statement(period='quarter', lang='en', dropna=True).head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Interest and Similar Income,Interest and Similar Expenses,Net Interest Income,...,General & Admin Expenses,Operating Profit before Provision,Provision for credit losses,Profit before tax,Tax For the Year,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Attributable to parent company,EPS_basis
0,ACB,2025,3,15049404000000,0.164628,4280589000000,0.105982,15049404000000,-8279694000000,6769710000000,...,-2713933000000,5670732000000,-288936000000,5381796000000,-1101207000000,-1081502000000,-19705000000,4280589000000,4280589000000,0
1,ACB,2025,2,14298695000000,0.146214,4881159000000,0.092326,14298695000000,-7614847000000,6683848000000,...,-2736160000000,6556384000000,-463039000000,6093345000000,-1212186000000,-1210700000000,-1486000000,4881159000000,4881159000000,0
2,ACB,2025,1,13327306000000,0.111758,3678266000000,-0.058164,13327306000000,-6968441000000,6358865000000,...,-2691892000000,5222736000000,-626128000000,4596608000000,-918342000000,-958551000000,40209000000,3678266000000,3678266000000,0
3,ACB,2024,4,13518376000000,0.080173,4545364000000,0.134560,13518376000000,-6438085000000,7080291000000,...,-2739350000000,5818946000000,-147675000000,5671271000000,-1125907000000,-1086127000000,-39780000000,4545364000000,4545364000000,1017
4,ACB,2024,3,12922067000000,-0.007819,3870395000000,-0.041407,12922067000000,-6040680000000,6881387000000,...,-2933714000000,5202287000000,-358243000000,4844044000000,-973649000000,-971306000000,-2343000000,3870395000000,3870395000000,0

#### Chỉ số tài chính

In [ ]:
finance.ratio(period='year', lang='vi', dropna=True).head()

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

  Meta          Chỉ tiêu cơ cấu nguồn vốn                      \
    CP   Năm Kỳ            TSCĐ / Vốn CSH Vốn CSH/Vốn điều lệ
0  ACB  2024  5                  0.064849            1.624825
1  ACB  2023  5                  0.067120            1.381365
2  ACB  2022  5                  0.068129            1.137679
3  ACB  2021  5                  0.083797            0.874127
4  ACB  2020  5                  0.106712            0.690102

  Chỉ tiêu khả năng sinh lợi                                         \
     Biên lợi nhuận ròng (%)   ROE (%)   ROA (%) Tỷ suất cổ tức (%)
0                   0.604064  0.217459  0.021215           0.040161
1                   0.642829  0.247997  0.024188           0.038760
2                   0.581646  0.264917  0.024106           0.041841
3                   0.506881  0.239026  0.019753           0.000000
4                   0.526866  0.243075  0.018557           0.000000

  Chỉ tiêu thanh khoản Chỉ tiêu định giá                                      \
     Đòn bẩy tài chính Vốn hóa (Tỷ đồng) Số CP lưu hành (Triệu CP)       P/E
0            10.352125   111219781710000                4466657900  6.663950
1            10.130151   100208500320000                3884050400  6.405255
2            10.401935    80720698890000                3377435100  5.962443
3            11.754104    59172663390000                2701948100  6.259839
4            12.540286    74573768250000                2161558500  9.899843


        P/B       P/S P/Cash Flow    EPS (VND)    BVPS (VND)
0  1.332585  3.318531   13.287540  3758.910661  18685.486972
1  1.412263  3.060127    2.698405  4130.928116  18268.547957
2  1.381289  2.803769    3.794240  4052.836722  17302.675335
3  1.317850  2.511147    1.482062  3554.008310  16617.976119
4  2.103741  4.106189    6.854672  3554.297975  16399.353985

In [ ]:
finance.ratio(period='quarter', lang='en', dropna=True).head()

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

    Meta                         Chỉ tiêu cơ cấu nguồn vốn  \
  ticker yearReport lengthReport               Debt/Equity
0    ACB       2025            3                  9.376240
1    ACB       2025            2                  9.704445
2    ACB       2025            1                  9.240355
3    ACB       2024            4                  9.352125
4    ACB       2024            3                  8.858604

                                                        \
  Fixed Asset-To-Equity Owners' Equity/Charter Capital
0              0.059079                       1.779669
1              0.061880                       1.697809
2              0.061005                       1.695161
3              0.064849                       1.624825
4              0.058881                       1.535128

  Chỉ tiêu khả năng sinh lợi                                                  \
       Net Profit Margin (%)   ROE (%) ROIC (%)   ROA (%) Dividend yield (%)
0                   0.632315  0.199167      0.0  0.019117           0.040161
1                   0.730292  0.201725      0.0  0.019587           0.038023
2                   0.578447  0.204361      0.0  0.020059           0.044053
3                   0.641974  0.217459      0.0  0.021215           0.041494
4                   0.562444  0.217115      0.0  0.021717           0.040568

  Chỉ tiêu thanh khoản        Chỉ tiêu định giá  \
    Financial Leverage Market Capital (Bn. VND)
0            10.376240             1.279027e+14
1            10.704445             1.350941e+14
2            10.240355             1.166021e+14
3            10.352125             1.076465e+14
4             9.858604             1.101031e+14

                                                                             \
  Outstanding Share (Mil. Shares)       P/E       P/B       P/S P/Cash Flow
0                    5.136657e+09  7.356915  1.399136  3.745308    7.833025
1                    5.136657e+09  7.958327  1.549055  3.984903   12.072349
2                    5.136657e+09  7.040078  1.339106  3.505677    8.617451
3                    4.466658e+09  6.411432  1.289771  3.211912   12.860632
4                    4.466658e+09  6.775292  1.396286  3.302936  -21.381995


     EPS (VND)    BVPS (VND)
0   833.341478  17796.692895
1   950.259942  16978.092134
2   716.081741  16951.605645
3  1017.620801  18685.486922
4   866.508042  17653.973632